### ISSUE TITLE
Running it on my dataset

### ISSUE THREAD

**Issue by neskulka** [yysijie/st-gcn#102]
### Other comments
Hello, I am naive to ST-GCN and the dataset I am using is similar to Kinetics-Skeleton. How can I test it on my own dataset? Thank you in advance.

**Comment by yjxiong** [comment]
Yes. What can we help you here?

**Comment by neskulka** [comment]
Thank you for the reply. I was able to run the demo on Kinetics-skeleton dataset.  To train it on my own I am unsure about the way .npy and .pkl files are created. If you can shade some light on that it will be helpful.

**Comment by yjxiong** [comment]
You can refer to 
https://github.com/yysijie/st-gcn/blob/master/tools/utils/openpose.py
https://github.com/yysijie/st-gcn/blob/master/tools/utils/ntu_read_skeleton.py

for how to load external data sources.

**Comment by yysijie** [comment]
@neskulka, there is a simple example:
```
{
    "video_name_1": {
        "has_skeleton": true,
        "label": "run"
        "label_index": 1
    }
    "video_name_2": {
        "has_skeleton": true,
        "label": "jump"
        "label_index": 2
    }
}
```
