### ISSUE TITLE
Data used for pretrained model

### ISSUE THREAD

**Issue by maxstrobel** [yysijie/st-gcn#103]
Hi guys,

thanks for sharing your great work!
I have a small question regarding the pretrained model you offer. Can you state which data you used for the training? To be more precise:
- Which dataset?
- Did you use all classes of that dataset or only a subset?

Thanks,
Max

**Comment by yjxiong** [comment]
These can found in the paper. Pretrained models are for their corresponding datasets.

https://arxiv.org/abs/1801.07455
