### ISSUE TITLE
Do you have NTU-RGBD trained model weight?

### ISSUE THREAD

**Issue by FesianXu** [yysijie/st-gcn#106]
Thanks for your work, i wanna develop my model based on your model and i wanna your NTU-RGBD trained model weight. Does it accessable now? Thanks

**Comment by FesianXu** [comment]
I found your weight file in baidu cloud but i dont know which one should i load if i just wanna use the st-gcn backbone network, is the ntuxsub-st_gcn.pt this one? it seems that there are may keys like backbone in this file.

**Comment by yjxiong** [comment]
NTU-RGBD has two evaluation protocols, cross-subject (X-sub) and cross view (X-view). So there are two pre-trained models, each for on protocol. You can choose the one you feel more appropriate for your application.

**Comment by FesianXu** [comment]
seems that the pretrained models cannot match the current code, but it can match the past version, do you have the current code's pretrained model?

**Comment by yjxiong** [comment]
You can then use the previous version. The current version is just to confirm pytorch 0.4 api.
