### ISSUE TITLE
multi-person and multi-action for training 

### ISSUE THREAD

**Issue by taxuezcy** [yysijie/st-gcn#109]
@yjxiong  @yysijie ,Hi, I have known that your project can get  multi-action in one video, but how to get multi-action in one frame, I mean that there are  many people in one frame and they have different actions, looking forward to your reply!

**Comment by yysijie** [comment]
Hi, @taxuezcy, 
Script `./processor/demo.py`give an example for perform action recognition. In this example, the shape of input data tensor is (N, C, T, V, M), where N is the batch size, C is the channel of the input data, T is the temporal size, V is the number of joints, and M is the number of people. Here we assume that, in a video, the actions of all people are the same.
To achieve your target, you should permute the shape to (N*B, C, T, V, 1).  In this case, the model will predict the action person by person.

**Comment by LucyLu-LX** [comment]
@taxuezcy  Hi, have you finished the multi-person and multi-action training?
Is the inference time the same as the original?
How is the result? 
Thx.

**Comment by yysijie** [comment]
@LucyLu-LX,
the inference time should be the same as the original version. The performance should be discussed case by case according to the utilized dataset. In NTU-DGB+D and Kinetics-skeleton, the accuracy is expected to slightly decrease because of missing multi-person information.

**Comment by vinayaksun** [comment]
@taxuezcy Did you implement this? If yes then please guide me
