### ISSUE TITLE
how to change the  input length of network?

### ISSUE THREAD

**Issue by huangzhenjie** [yysijie/st-gcn#118]
Hi!
@yysijie 
I'm sorry to bother you.
I built a database similar to Kinetics, but it length shorter than Kinetics. According to my person undertanding,  if the input is less than the preset length, it would random sample sub-sequencd with the same window, for example, when input is 100 frame, and the preset length is 300, then the finally input is 300 frames. When the model is trained, enter a long video,  the length of the input is 300 frames. Is it right? Could you tell me how to change the input length of network, because my train dataset is too short.
Thank you very much.

**Comment by Zakeiswo** [comment]
I think you just need to change the window_size in train.yaml, or make your length longer in #97 .

**Comment by yysijie** [comment]
Hi, @huangzhenjie,
you can set the skeleton length according to your typical length in your dataset.
Our model is not sensitive to this hyper-parameter.
