### ISSUE TITLE
【Kinetics Dataset】Data Corrupted or incomplete from Baiduyun or Google Drive

### ISSUE THREAD

**Issue by czqInNanjing** [yysijie/st-gcn#12]
Hi! Thank you for your great jobs!

But when I download the  Kinetics dataset from the link your provided, the unarchiver remind me that the data is corrupted(from Baiduyun) or incomplete(from Google Drive). 

If I continue to unarchive the zip file and run the  command "python tools/kinetics_gendata.py --data_path <path to kinetics-skeleton>"

The process would fail during the check

```
Traceback (most recent call last):----------------            ]
  File "tools/kinetics_gendata.py", line 84, in <module>
    gendata(data_path, label_path, data_out_path, label_out_path)
  File "tools/kinetics_gendata.py", line 57, in gendata
    data, label = feeder[i]
  File "/home/qiang/Software/st-gcn/st_gcn/feeder/feeder_kinetics.py", line 131, in __getitem__
    assert (self.label[index] == label)
AssertionError
```

I guess it is because the file is incomplete. Can you give some advice?

**Comment by yysijie** [comment]
Hi! Thank you for reporting this problem. I will check it as soon as possible.

**Comment by yysijie** [comment]
@czqInNanjing 
Hi, both documents in Baiduyun and Google Drive are correct, and the script for building database works well on my server. 
I am wondering how you unarchive the zip files on Baidu Yun.
Since users can not directly download large documents in BaiduYun from the browser. I split the zip document into 2 segments. To extract files from multiple zip segments, you should:
1. collect 2 parts together.
2. run `zip -F kinetics-skeleton.zip --out merge.zip`
3. run `unzip ./merge.zip`

**Comment by czqInNanjing** [comment]
Thank you for your kind answer!

I unarchive the zip both in Mac and in Ubuntu 16.04.
In mac, using the "Unarchive"
In ubuntu, using the default "Archive Manager" to unarchive.
Under both situation, it reports file is corrupted.

But, we still continue to build with these files.
Although the script for building dataset still failed on my PC and my collaborator's PC, we found that it only fail for 4 samples by change the code

instead of "assert", we print the sample that does not match
`assert (self.label[index] == label)  feeder_kinetics.py Line 131`
===>
`print(self.label[index])`

 so we jump through these samples and successfully build the dataset.

The code now work well.

**Comment by xueyingliu** [comment]
The Baiduyun link is out of date, can you provide a new one? I can not download file from Google Drive.

**Comment by nobody-cheng** [comment]
> The Baiduyun link is out of date, can you provide a new one? I can not download file from Google Drive.

请问有百度云吗
