### ISSUE TITLE
Method for fusion with TSN model

### ISSUE THREAD

**Issue by huanglai666** [yysijie/st-gcn#122]
Thank you for your work on skeleton motion recognition.
 I noticed the discussion part of the paper and discussed the use of the STGCN network instead of flow tsn as the input to the two stream method and achieved good results. I know that the weighted averaging method was taken in the original TSN paper for model fusion. Is the fusion of the three models we explore here the same? If I want to reproduce the accuracy in the paper, what is the ratio of the RGB:flow:STGCN model?
Congratulations again on your work for superior results.Looking forward to hearing from you.

**Comment by yjxiong** [comment]
Yes its the same. Normally 1:0.5:0.5 should suffice.
