### ISSUE TITLE
Questions about the pre-training model

### ISSUE THREAD

**Issue by hd120105** [yysijie/st-gcn#123]

**Comment by hd120105** [comment]
@yysijie @yjxiong ,hello, sorry to interrupt you, I am naive to ST-GCN and I have built my own dataset which is much smaller than kinetics, there are 99 classes. I use my dataset to fine-tune the pre-trained model you gave and modified num_classes in train.yaml, but with the following error:
Mismatch for fcn.weight:copying a param of torch.size([99,256,1,1]) from checkpoint,where the shape is torch.Size([400,256,1,1]) in current model
If you can, can you tell me where to fix this problem?Thank you!

**Comment by hd120105** [comment]
@yysijie @yjxiong ,hello, sorry to interrupt you, I am naive to ST-GCN and I have built my own dataset which is much smaller than kinetics, there are 99 classes. I use my dataset to fine-tune the pre-trained model you gave and modified num_classes in train.yaml, but with the following error:
Mismatch for fcn.weight:copying a param of torch.size([99,256,1,1]) from checkpoint,where the shape is torch.Size([400,256,1,1]) in current model
If you can, can you tell me where to fix this problem?Thank you!

**Comment by hd120105** [comment]
@yysijie @yjxiong ,hello, sorry to interrupt you, I am naive to ST-GCN and I have built my own dataset which is much smaller than kinetics, there are 99 classes. I use my dataset to fine-tune the pre-trained model you gave and modified num_classes in train.yaml, but with the following error:
Mismatch for fcn.weight:copying a param of torch.size([99,256,1,1]) from checkpoint,where the shape is torch.Size([400,256,1,1]) in current model
If you can, can you tell me where to fix this problem?Thank you!

**Comment by liqier** [comment]
I encountered the same problem, how did you solve it?
