### ISSUE TITLE
Running pretrained modes error:  cannot import name 'import_class'

### ISSUE THREAD

**Issue by thekoshkina** [yysijie/st-gcn#125]
I'm getting an import error when i try to test  the pretrained models

### Steps to reproduce the behavior
st-gcn-master$ python3 main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml

### Actual behavior
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from torchlight import import_class
ImportError: cannot import name 'import_class'

### Code version (Git Hash) and PyTorch version
torchlight-1.0-py3.5
### Dataset used
kinetics -skeleton

**Comment by thekoshkina** [comment]
Update: I managed to get it solved by:
1. adding an empty __init__.py to the folder torchlight.egg-info/
2. changing **from torchlight import ...** to **from torchlight.torchlight import ..** 
3. changing **import torchlight** to **import torchlight.torchlight as torchlight**

**Comment by junwenchen** [comment]
Did you solve it?
