### ISSUE TITLE
Crash due to mismatch of video length and json files

### ISSUE THREAD

**Issue by yaseryacoob** [yysijie/st-gcn#126]
### Code version (Git Hash) and PyTorch version
PyTorch
### Dataset used
Own dataset
 
I process a video of let's say 10K frames with openpose and use their json output. There are hundreds of frames without any person detections, so there are no json files for these frames. When you code loads the json files, it creates a mismatch between the json entities and video length. It appears to me that you expect a json for every frame, even if there are no people in the frame? 

THe crash happens in video.py  at the line

data_numpy[0, frame_index, :, m] = pose[0::2]
(sincethere are no detections for specific frame_index).

**Comment by yjxiong** [comment]
yes. there should a JSON for each frame
