### ISSUE TITLE
How to train st-gcn using kinetics-skeleton dataset?

### ISSUE THREAD

**Issue by pingqi** [yysijie/st-gcn#128]
### Code version (Git Hash) and PyTorch version
0.4.0
### Dataset used
kinetics-skeleton dataset
### Actual behavior
training
### Other comments

Hi, I want to train st-gcn and I have downloaded the kinetics-skeleton json file , but where is the source kinetics clip video from? In kinetics_600_readme.txt , there is "http://youtu.be/${youtube_id}".It means , getting the video from youtu.be while traing the st-gcn   or getting the video before training the st-gcn?
So, how can I get the kinetics dataset? or it do not need the dataset.
Bests,

**Comment by yjxiong** [comment]
You don't need the Kinetics video dataset. The skeleton information is already extracted and stored in the data files you downloaded following the README.

**Comment by yysijie** [comment]
Hi @pingqi, this is a codebase for skeleton-based action recognition.
Only the coordinates of skeleton joints will be considered in this model. 
If you are interested in video-based action recognition, [here](https://github.com/yjxiong/temporal-segment-networks) is a good codebase for you.

**Comment by pingqi** [comment]
@yysijie @yjxiong  Thank you very much. I see.
