### ISSUE TITLE
Alternative to human pose estimation

### ISSUE THREAD

**Issue by huanglai666** [yysijie/st-gcn#129]
Thank you for your contribution to motion recognition. st-gcn is an excellent framework. I am verifying whether the framework is universal for human pose estimation methods. I don't know if you have used data from human poses other than openpose.

**Comment by yysijie** [comment]
@huanglai666, sure you can.
Please follow the discussion in #11 and #22.
You can convert OpenPose or other pose estimators' output to our format and train on your own data.
