### ISSUE TITLE
Visulization of ST-GCN in Action

### ISSUE THREAD

**Issue by kampta** [yysijie/st-gcn#13]
`README` file contains some visualizations showing neural response magnitude of each node in the last layer of our ST-GCN.

Would you be sharing the code for same?

**Comment by zoukai214** [comment]
Has the visualizations code been sharing?

**Comment by yjxiong** [comment]
@orapradeep 
You are welcome to send a PR. It is not on our plate right now because the pose estimation part involves a lot of dependencies.

**Comment by yysijie** [comment]
Hi, @kampta, @zoukai214, @orapradeep, 
thank you for your interest. We have released a new version, which includes a demo for skeleton-based action recognition and feature visualization. You can feed your custom videos or wild videos into the demo script as long as Openpose can find human skeletons. :)

Please update to the latest master branch. And follow our guide to setup the codebase.

**Comment by kampta** [comment]
Thanks @yysijie
