### ISSUE TITLE
The necessity of two-dimensional skeleton confidence

### ISSUE THREAD

**Issue by huanglai666** [yysijie/st-gcn#130]
Thank you very much for your work.
Why (x, y, z) can be used as input when inputting a 3D skeleton, (x, y, c) when using a 2D skeleton, is confidence required input, and can (x, y) be used as input? Can this get a  accurate prediction?
@yjxiong @yysijie

**Comment by yysijie** [comment]
Hi @huanglai666.
Sure. But with different inputs, you should train the model from scratch by yourself.

**Comment by pingqi** [comment]
@huanglai666 @yysijie, Hi, what does 3D skeleton and 2D skeleton mean? what is the difference between them? In my opinion, 3D skeleton mean video, 2D skeleton mean picture, is it right? If it is right, does the z of (x,y,z) mean the frame index? or does the z of (x,y,z) mean the location as (x,y)?

**Comment by yjxiong** [comment]
@pingqi 
3D skeleton has joint coordinates in the form of (x,y,z), where x is on the  horizontal axis, y the vertical axis, and z the depth axis. Then 2D skeleton means there is not depth information.


See the LHS in the figure below.

![image](https://user-images.githubusercontent.com/6830199/52829210-b6a93380-3080-11e9-985d-bcd49948f1e3.png)
