### ISSUE TITLE
Output Size

### ISSUE THREAD

**Issue by LucyLu-LX** [yysijie/st-gcn#131]
@yysijie @yjxiong 

I am confused about output size.
I think it is  [class_num, X,  joints_num, person_num]
Does X mean every 4 frames we have a prediction of action, as #120 described?

If so, is the prediction of action for the 4 frames independent or relayed on the predictions of  latter frames.
Cause I printed the label_name_sequence
`label_name_sequence = [[label_name[p] for p in l ]for l in label_sequence]`
and I found out label_name_sequence  didn't stay the same when the input frames number changed.
for example, in ta_chi.mp4
when frames_num = 300, the first output of label_sequence is 'throwing discus'
but frames_num = 40, the first output of label_sequence is 'stretching arm'

**Comment by yysijie** [comment]
Hi @LucyLu-LX,
Yes, every 4 frames we have a prediction of action. However, it does not mean the receptive field of each prediction includes only 4 frames. They overlap.
