### ISSUE TITLE
How to save and load parameters so that I can continue training the next day

### ISSUE THREAD

**Issue by paduma** [yysijie/st-gcn#132]
I use two GPU gtx 1080 for training, it prompts I need a long time to finish training, but everyday I spend up to 10 hours in lab because the lab is powered off at night .I  want to konw how to save and load parameters so that I can continue training the next day.

Fuctions torch.save() and load_state_dict() in PyTorch seems helpful, but I don't know in which files I should use them and how to use. Can you help me?

**Comment by paduma** [comment]
It takes about 2 hours one epoch, so I guess a long time I need to finish 60 epochs.

**Comment by yysijie** [comment]
Hi, please set ```weights``` and ```start_epoch``` in the training configuration file. Or you can directly appoint it in the command line, for example, to continue the training of epoch **10**:
```
python main.py recognition -c config/st_gcn/<dataset>/train.yaml [--work_dir <work folder>] --weights <work folder>/epoch10_model.pt --start_epoch 10
```
