### ISSUE TITLE
use pretrained model on my data. convert to NTU RGB+D format

### ISSUE THREAD

**Issue by thekoshkina** [yysijie/st-gcn#134]
I want to use pre trained NTU RGB+D model on my own dataset with 3d skeleton points.

When I was looking at the original NTU RGB+D data I noticed that some x,y coordinates are negative. 

Why does that happen and how can I make sure my data is in the same format

**Comment by yysijie** [comment]
Hi, the format of NTU-RGB+D is not defined by us. Please see the official [github code](https://github.com/shahroudy/NTURGB-D/tree/master/Matlab), which illustrate how to map joint coordinates to the real 3D world.

**Comment by thekoshkina** [comment]
To plot the joints onto the image they have a special set of the coordinated (depthx, depthy, rgbx, rgby).

There's no information about how the transform these to x,y, z that you use for the model training. 

I suspected that to obtain x they subtract half of the image width (1920/2) from the rgbx coordinate and then divide the difference by this half width  (960), but when i tested it my x was slightly off from theirs.

**Comment by yysijie** [comment]
We have the same assumption as you. We once tested it on images with height 256. It works.

**Comment by thekoshkina** [comment]
thank you

**Comment by lxy5513** [comment]
@thekoshkina  @yysijie 
Hi,  I want to visualize the NTU 3D joints, but I don't the NTU dataset 3D joints' format. Is it in space coordinate or camera coordinate? before it input into ST-GCN, Do it some normalization process?  

Sincerely hope that you can reply? thank you in advance?

**Comment by thekoshkina** [comment]
@lxy5513 
it's camera coordinates
