### ISSUE TITLE
openpose.bin not found

### ISSUE THREAD

**Issue by HARIHARAN1103** [yysijie/st-gcn#135]
We have tried the demo model we got an error as follows.
sh: 1: openpose/examples/openpose/openpose.bin: not found

openpose.bin not found in openpose directory.
please suggest where to find the file or suggest an alternate solution for this issue.

**Comment by Shanmugavadivelugopal** [comment]
I to tried this model , got the same issue please suggest the solution for this issue.

**Comment by yysijie** [comment]
@HARIHARAN1103, @Shanmugavadivelugopal,
Please refer to https://github.com/yysijie/openpose for the installation guidance.
If you use the default setting to build openpose, the .bin file will be generated at path ```./build/examples/openpose/openpose.bin```.
