### ISSUE TITLE
Understanding Einsum

### ISSUE THREAD

**Issue by hondaathma** [yysijie/st-gcn#138]
Hi,
Thanks a lot for the really useful implementation.
I have a question regrading the following einsum operation. How exactly does the adjacency matrix get multiplied with the X matrix.??
x = torch.einsum('nkctv,kvw->nctw', (x, A))
x input dimension is (128,3,64,150,18)
A dimension is (3,18,18)
x output dimension is (128,64,150,18)

Can you please help me understand by breaking down the matrix multiplication steps?

**Comment by yysijie** [comment]
```Y = torch.einsum('nkctv,kvw->nctw', (X, A))``` means:

![codecogseqn](https://user-images.githubusercontent.com/9592362/53620316-783d7800-3c2d-11e9-8b3f-6322a921f0d9.gif)
For more information about einsum, please refer to https://pytorch.org/docs/stable/torch.html#torch.einsum.
