### ISSUE TITLE
how to calc matrix A

### ISSUE THREAD

**Issue by zhezh** [yysijie/st-gcn#14]
I am a little confused about how to calculate A. Could you please describe it use a demo matrix?  
I saw A is of shape (3,18,18)  when test on Kinetics,  of which dim 0 is an eye matrix and dim 1 is adjacency matrix.  
In the paper end of para 2, sect 3.6: 
$ \Lambda^{-0.5}(A+I)\Lambda^{-0.5} $ on the second dimension.

If we now have a adjacency matrix of a 4-node graph, say [[0,1,1,1],[1,0,1,0],[1,1,0,0],[1,0,0,0]]
could you please give the result of $\Lambda$  for both uni and multi partitioning strategies?

Thanks

**Comment by zhezh** [comment]
![258529642](https://user-images.githubusercontent.com/29795174/38077975-6b5d2c80-336d-11e8-8d6f-81faa1b3f889.jpg)

Am I correct ?

**Comment by zhezh** [comment]
@yysijie Thanks~ The code tells everything~

**Comment by JasOlean** [comment]
I do not find the above link. [ https://github.com/yysijie/st-gcn/blob/master/st_gcn/graph/tools.py](url)

**Comment by khadijakhaldi** [comment]
please what about if the strategy is uniform? why the adjacency matrix is 3d?
