### ISSUE TITLE
--openpose <path to openpose build directory>

### ISSUE THREAD

**Issue by chaoshengzhe** [yysijie/st-gcn#141]
I do not find the file? I scan the problem,some people think that it lacks openpose.bin,and they give a url:https://github.com/CMU-Perceptual-Computing-Lab/openpose#installation-reinstallation-and-uninstallation,but,after the guidance of the install,I can not get the openpose.where is my problem?Help me!

**Comment by yysijie** [comment]
```openpose.bin``` should be under the ```<path to openpose repo>/build``` if you installed it addcoding to the official guidance.

**Comment by Tylerjoe** [comment]
maybe you didn't make install
1. cmake ..
2.make install
