### ISSUE TITLE
How to replace openpose?

### ISSUE THREAD

**Issue by Yangmt123** [yysijie/st-gcn#145]
Can openpose be replaced with other skeleton sequences? And,which files need to be modified?

**Comment by durianno1** [comment]
I also have this question，I used other openpose projects to extract 18 key points from each frame of the video.but how can i modify these data ,and put them into the action recognition demo.

**Comment by Txj8811** [comment]
The demo create a cmd of openpose to run a video and save a json file of skeleton , then load the file and use the 18key points. I think it can be easy replaced with other projects.

**Comment by Yangmt123** [comment]
@Txj8811  I want to use this method in the hand skeleton and training, how to change the body skeleton into the skeleton of the hands?

**Comment by Txj8811** [comment]
@Yangmt123 I'm consider to use 25 key points instead of 18 key points model. Maybe your question is the same like mine. I think how to redefine the new spatial configuration partitioning struct is the key of this issue.

**Comment by Yangmt123** [comment]
@Txj8811  Yes,I am also the 25 key points of using hand.Can you add a WeChat exchange?

**Comment by Txj8811** [comment]
@Yangmt123 txj8811

**Comment by Tylerjoe** [comment]
@Yangmt123 @Txj8811 have you find the way to use 25 keypoints to make the action recognition? Thanks

**Comment by CompliceU** [comment]
Hello, don't know if you have completed the task of this change. @Txj8811 @Yangmt123

**Comment by aa12356jm** [comment]
@CompliceU @Txj8811 @Tylerjoe @Yangmt123  have you  completed the task of this change？can you exchange wechat ?,my wechat is 18575591615
