### ISSUE TITLE
the accurary is lower than 31.6%(kinetics datasets)

### ISSUE THREAD

**Issue by Tylerjoe** [yysijie/st-gcn#146]
I have used the provided model, but why my test accuracy of the kinetics dataset is lower than yours, Could you please tell me the possible problem or reason, Thanks!

![image](https://user-images.githubusercontent.com/11598641/54015517-e13b6780-41ba-11e9-9350-3ad5eec57bd4.png)

**Comment by yysijie** [comment]
Hi, @Tylerjoe,
Please update to the latest version and download pre-trained models again.
