### ISSUE TITLE
Hi! What is the train_data.npy contact with the json files which are in the kenetics_train folder? And Which one is used when training the dataset? Thank you, I am looking forward to your reply.

### ISSUE THREAD

**Issue by wwwpbai** [yysijie/st-gcn#147]

**Comment by durianno1** [comment]
I also want to know how skeleton key points  should be stored in train_data.npy,and how to write the tain_label.pkl

**Comment by wwwpbai** [comment]
@durianno1 , .pkl and .npy file are just json's other forms of expression. you can use json files you have generated to call kinetics_gendata function, please see the official [github code ](https://github.com/yysijie/st-gcn/blob/master/tools/kinetics_gendata.py).

**Comment by yysijie** [comment]
@wwwpbai, thank you for your help.

**Comment by wwwpbai** [comment]
@yysijie, no thanks, I have a question about training, you can see it [here](https://github.com/yysijie/st-gcn/issues/157), thank you
