### ISSUE TITLE
About the result of json_pack function

### ISSUE THREAD

**Issue by wwwpbai** [yysijie/st-gcn#149]
@yysijie @yjxiong, hello, I use new dataset to generate json files which use json_pack function, but i find the frame_index of the json files are out of order and index is starting from zero. So i want to know does this situation affect training?

**Comment by Txj8811** [comment]
The order will be re-order in the program. So I think it doesn't matter.

**Comment by wwwpbai** [comment]
@Txj8811 , thanks, and how about the frame_index is starting from zero?

**Comment by Txj8811** [comment]
@wwwpbai it's expected.

**Comment by wwwpbai** [comment]
@Txj8811 ,i download the database from the st-gcn in github, but the frame_index of the json file is starting from one.

**Comment by wwwpbai** [comment]
I use frame_index as key to sort in json files. And when i train the dataset,the index is starting from zero that does't matter.
