### ISSUE TITLE
can't run demo correctly

### ISSUE THREAD

**Issue by Florencexiran** [yysijie/st-gcn#150]
Sorry to bother you. I get an error when I run this command：

sudo python main.py demo  --openpose /home/fjt/openpose/build --video resource/media/skateboarding.mp4
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
OpenPose demo successfully finished. Total time: 32.509077 seconds.
*** Error in `/home/fjt/openpose/build/examples/openpose/openpose.bin': free(): invalid pointer: 0x0000000001afe130 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f5ad54a67e5]

......

......

(core dumped)
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/home/fjt/st-gcn/processor/demo.py", line 47, in start
    video = utils.video.get_video_frames(self.arg.video)
  File "/home/fjt/st-gcn/tools/utils/video.py", line 33, in get_video_frames
    vread = skvideo.io.vread(video_path)
  File "/usr/local/lib/python3.5/dist-packages/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/usr/local/lib/python3.5/dist-packages/skvideo/io/ffmpeg.py", line 44, in __init__
    super(FFmpegReader,self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/skvideo/io/abstract.py", line 116, in __init__
    "No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

python 3.5
skvideo 1.1.11
openpose latest version

I really need your help.Looking forward to your reply.Thank you very much!

**Comment by Florencexiran** [comment]
I have solved this problem.
I used source code to complie ffmpeg and solved it.

**Comment by yysijie** [comment]
Thank you.
