### ISSUE TITLE
How to use the openpose's FlAG argument ?

### ISSUE THREAD

**Issue by ro6842** [yysijie/st-gcn#152]
Now I am using the command ： 
[ python main.py demo --openpose /dataa/openpose/build --video /data/video_testing.mp4 ]
to test the stgcn.

But How can I use the openpose's FlAG argument to speed up like : "--net_resolution"
If I want to run the OpenPose, I just need to type the command like：
[ ./build/examples/openpose/openpose.bin --model_pose COCO --video /data/video_testing.mp4 --camera_fps 30.0 --net_resolution 320x176 ] 

But If I want to run the STGCN, I typ the command like：
[ python main.py demo --openpose /dataa/openpose/build --net_resolution 320x176 --video /data/video_testing.mp4 ]
It will be Errors. Says : the command " --net_resolution" NOT FOUND.

Can anyone help me how to use the openpose's FlAG argument when I run STGCN?
Thank you very much!

**Comment by Txj8811** [comment]
You can modify the **openpose_args** which set in the processor/demo.py.

**Comment by ro6842** [comment]
Thank you, I got it!

**Comment by yysijie** [comment]
@Txj8811 Thank you for your help.
