### ISSUE TITLE
how  does this parameter affect the network performance?

### ISSUE THREAD

**Issue by zz-ycx** [yysijie/st-gcn#155]
hello, i want to know the fourth parameter in st_gcn.py mean? 
`         self.st_gcn_networks = nn.ModuleList((
            st_gcn(in_channels, 64, kernel_size, 1, residual=False, **kwargs),
            st_gcn(64, 64, kernel_size, 1, **kwargs),
            st_gcn(64, 64, kernel_size, 1, **kwargs),
            st_gcn(64, 64, kernel_size, 1, **kwargs),
            st_gcn(64, 128, kernel_size, 2, **kwargs),
            st_gcn(128, 128, kernel_size, 1, **kwargs),
            st_gcn(128, 128, kernel_size, 1, **kwargs),
            st_gcn(128, 256, kernel_size, 2, **kwargs),
            st_gcn(256, 256, kernel, 1, **kwargs),
            st_gcn(256, 256, kernel_size, 1, **kwargs),
        ))
`
i try to change the fourth parameter 1(stride) to 2 or other number, and it didn't report any error, so what this parameter mean and what effect does it have to the whole program ? can anyone give some idea about question? Thanks a lot !

**Comment by zz-ycx** [comment]
@yysijie could you give aome advice about this parameter? Thanks a lot.

**Comment by yjxiong** [comment]
https://github.com/yysijie/st-gcn/blob/master/net/st_gcn.py#L125

It is the temporal stride for the temporal side convolution. Setting it to 2 will make a sequence of length T be subsampled to length [T/2].
