### ISSUE TITLE
IndexError:boolean did not match indexed array along dimension 1: dimension is 283 but corresponding boolean dimension is 358

### ISSUE THREAD

**Issue by Yxiaoqian** [yysijie/st-gcn#159]

**Comment by Yxiaoqian** [comment]
when I use my own video(.avi) to run the demo, it gives me this error, how can I handle it?

**Comment by MengXinChengXuYuan** [comment]
Hi for those who are stuck by this error, you can simply modify the code in visualization.py, line 109 to 112:
`       blend(frame, text_1)
        blend(skeleton, text_2)
        blend(skeleton_result, text_3)
        blend(rgb_result, text_4)`
into:
`       # blend(frame, text_1)
        # blend(skeleton, text_2)
        # blend(skeleton_result, text_3)
        # blend(rgb_result, text_4)`

These codes are used to blend the resource image on the result video (which is not that necessary), and seem not compatible with some resolution cases (for me the resolution of my video is 540 * 960).

**Comment by yysijie** [comment]
@MengXinChengXuYuan,
Thank you for your kind help. 
In the new version, we simply added "try-except" statements to avoid this error.
