### ISSUE TITLE
[Kinetics Skeleton] Sample corruption? (sample has completely zero values only)

### ISSUE THREAD

**Issue by Minju-Jung** [yysijie/st-gcn#16]
Hi!
Thank you for providing a nice code.

I downloaded Kinetics-skeleton from GoogleDrive and followed the rebuild process as follows:
`python tools/kinetics_gendata.py --data_path <path to kinetics-skeleton>`

Based on your code, I revised to stacked GRU and it worked in NTU RGB+D dataset.
But, it is not working well in Kinetics-skeleton.
I found that my problem is occurred by some wrong samples as follows:
- For example, in "kinetics_val_label.json", "_2siVCR5EBs.json" has True "has_skeleton", but actually "_2siVCR5EBs.json" has completely empty skeleton values over all time steps. Hence, ignore_empty_sample in "feeder_kinetics.py" is not working properly.
- Also, "_2hHyXxsyFo.json" in "kinetics_val", sample has mixed exist-skeleton and empty-skeleton values over time steps as like [0,0,1,1,0,0,0,0,0,1,1,1,1] ( 0 is empty-skeleton and 1 is exist-skeleton). But, I think that blank between exist-skeletons might induce discontinuity.

Are these problems what you intend or mistake?
I will really appreciate if you give me an answer.

**Comment by yjxiong** [comment]
@yysijie Mind having a look?
