### ISSUE TITLE
static actions like standing, lying for single frame

### ISSUE THREAD

**Issue by ll490187880** [yysijie/st-gcn#165]
Hello!
For some static actions like standing, lying and so on , how can I convert the st-gcn to s-gcn? Will it be better than simple classification with RGB images?

**Comment by yjxiong** [comment]
You can remove all temporal convolution and temporal pooling operators to model single frame input. We didn't experiment with this so I cannot tell whether it will work.

**Comment by Cambrainnnnn** [comment]
@ll490187880 i'm also trying to recognizing static actions by skeletons. Maybe we could exchange some ideas and informations. this is my qq:401105480
