### ISSUE TITLE
about "window_size" in train.yaml

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [yysijie/st-gcn#171]
hi!
It seems that I didn`t fully understand the paper and the code
In section 4.1 the paper said for kinetics the length of the video is always padded to 300
So in kinetics_gendata.py the data are loaded as [3 300 2 18] for each sample
But in training phase the data is than loaded as [batch 3 150 1 18], which 150 is the window size given in train.yaml
Did I just miss something?
What does the window size in train.yaml mean? Which one is the true video length for training?

**Comment by MengXinChengXuYuan** [comment]
Also I found the code in feeder.feeder.Feeder, __getitem__ function, there will be a random choose in the input 300 sequences to pack a 150 length data.
Does it mean, you always pad the origin video to 300 frames, and in training phase in every batch you random choose 150 frames to feed every iter?

**Comment by yysijie** [comment]
Yes, we random choose 150 successive frames  from 300 frames.
