### ISSUE TITLE
Size of Kernal in Spatial Partition

### ISSUE THREAD

**Issue by zye1996** [yysijie/st-gcn#173]
![image](https://user-images.githubusercontent.com/28901953/56253400-2a1fef00-608a-11e9-8f7a-e5b053bfe12d.png)
Hi,

I am looking into your paper and code and I noticed that you are using openpose toolkit in extracting the pose.

The limb connection you specified in graph.py says joint 8 is connected to joint 2 but it seems not the case by the explanation of openpose. 

If I am understanding your paper correct, would the spatial kernel size in this case would be 5 instead of 3?

**Comment by yysijie** [comment]
Hi, although we defined the skeleton joints following Openpose in kinetics-skeleton dataset, the skeleton graph can be constructed in different ways. We have not explored the effect of different graph designs.
