### ISSUE TITLE
when i run the pretrained model, i got a problem.

### ISSUE THREAD

**Issue by hacker-wei** [yysijie/st-gcn#189]
![图片](https://user-images.githubusercontent.com/32689594/58416098-16b56a00-80b3-11e9-9032-971707ed9114.png)
input this order in terminal: python3 main.py recognition

**Comment by PrettyZZW** [comment]
问题解决了么，请问是怎么解决的

**Comment by hacker-wei** [comment]
因为那是旧的模型，所以你得重新训练你的模型，这样的话，就可以跑了
