### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by bryancresswell** [yysijie/st-gcn#19]
### Code version (Git Hash) and PyTorch version
6542289, 0.3.1, running Python 3.6.4
### Dataset used
NTU-RGB-D
### Expected behavior
Generate the data
### Actual behavior
`FileNotFoundError: [Errno 2] No such file or directory: 'data/NTU-RGB-D/samples_with_missing_skeletons.txt'`
### Steps to reproduce the behavior
I downloaded the NTURGB skeleton file, unzipped it, placed it into the data folder under NTU RGB D, and ran the code. It would give me that error.

**Comment by RMobina** [comment]
you should copy the file in this path:
data/NTU-RGB-D/nturgbd+d_skeletons

**Comment by yysijie** [comment]
This bug has been fixed.
Sorry for any inconvenience.
