### ISSUE TITLE
About Top 1 and Top 5? What are they?

### ISSUE THREAD

**Issue by JasOlean** [yysijie/st-gcn#196]
### Other comments
In accuracy, there are Top 1 and Top 5. So, I would like to know what is the difference between them and what do they represent? Although I read about your paper, I am not clear about these these values. Could you explain that? And after training, how to test custom video using trained model weights one by one?

**Comment by vivek87799** [comment]
While training a single video clip may fall under more than one class but would have annotated only for one class. 
So we try to get the top 5 predictions while testing.
