### ISSUE TITLE
Where is sampling part in your code?

### ISSUE THREAD

**Issue by JasOlean** [yysijie/st-gcn#198]
### Other comments
I read your paper. There are two parts for sampling and partition. Could you show me sampling part in your code?

**Comment by yysijie** [comment]
@JasOlean, 
The sampling and partition operation have been combined.
They are equivalent to the formulation (10) in the paper, which corresponds to [this script](https://github.com/yysijie/st-gcn/blob/master/net/utils/tgcn.py).
