### ISSUE TITLE
Why in_channels is 3 for 2D coordinates?

### ISSUE THREAD

**Issue by JasOlean** [yysijie/st-gcn#203]
### Other comments
To train OpenPose data, there are 2D coordinates (x,y) with (2 x 18 = 36) points. For NTU data, there are 3D coordinates (x,y,z) with (3 x 25 = 75) points. But, when I trained for OpenPose, why in_channels are 3 since our input coordinates are (2 x 18 = 36) points? But before training, our input data dimension is (54 = 18 x 3) points. So, what is the 3rd dimension value for OpenPose data?
Please help me this question.

**Comment by djr2015** [comment]
OpenPose outputs (x,y,confidence) for each keypoint, I believe the 3rd dimension is the confidence value

**Comment by yjxiong** [comment]
Yes. The 3rd dimension corresponds to confidence scores.
