### ISSUE TITLE
14137 bus error (core dumped) 

### ISSUE THREAD

**Issue by XyliaYang** [yysijie/st-gcn#204]
Hi.I am rebuilding the datasets kinetics-skeleton using python tools/kinetics_gendata.py --data_path  /data1/home/yangxin/data/kinetics-skeleton/kinetics-skeleton .
But only half of the data is compiled,(145311/240436) Processing data: 
then this error appears: 14137 bus error (core dumped)  .
How can I fix this problem?

**Comment by yysijie** [comment]
@XyliaYang ,
Hi, I think it is a system error.
Please check if there are enough memory and disk space. 
Does this error always happen on the processing of the same sample (145311)?

**Comment by yysijie** [comment]
@XyliaYang,
README.md has been updated. You can download preprocessed data from Google Drive directly.
