### ISSUE TITLE
Why Temporal Modeling Can be Done By 1D Conv on the Temporal Axis?

### ISSUE THREAD

**Issue by CaesarPan** [yysijie/st-gcn#205]
Hi,

Thank you for sharing the great work! I'm wondering how the temporal modeling scheme in the paper that "connects the same body joint across time" can be done by the 1d conv in the implementation. cuz seems there's not explicit body joint matching part in the temporal branch. Any insight is greatly appreciated!

**Comment by khadijakhaldi** [comment]
Please any answer ?
