### ISSUE TITLE
About train_label.json 

### ISSUE THREAD

**Issue by ZhaoyiboL** [yysijie/st-gcn#206]
Due to the reason that I want to use my own datasets, so could you tell me how to generate the train_label.json file,I can't find a way of generating it? I would be appreciate it if you could reply to me! thank you.

**Comment by daylightsaving2017** [comment]
I have implemented the whole process of the st-gcn algorithm based on a totally new dataset. So I indeed suggest that you could write a new python script to complete the auto-labelling by saving the essential information to the json like the kinectics-skeleton format.

**Comment by daylightsaving2017** [comment]
@ZhaoyiboL

**Comment by ZhaoyiboL** [comment]
Thank you ,I have solved this problem so i didn't login in github these days. It's very kind of you.

**Comment by ZhaoyiboL** [comment]
@daylightsaving2017

**Comment by nanhui69** [comment]
> I have implemented the whole process of the st-gcn algorithm based on a totally new dataset. So I indeed suggest that you could write a new python script to complete the auto-labelling by saving the essential information to the json like the kinectics-skeleton format.

could you share you data preocesses script that for generate correct  train_label file ?
