### ISSUE TITLE
Error while running demo

### ISSUE THREAD

**Issue by TalBarami** [yysijie/st-gcn#208]
Hey,
While trying to test the demo file on windows I encountered the following problem:
PS C:\research\st-gcn-master> python main.py demo --openpose "C:\research\openpose-1.5.0-binaries-win64-gpu-python-flir-3d_recommended\bin\OpenPoseDemo.exe" --video "C:\research\st-gcn-maste
r\wave.mp4"
Starting OpenPose demo...
Starting thread(s)...

Error:
Caffe trained model file not found: models\pose/coco/pose_iter_440000.caffemodel.
Possible causes:
        1. Not downloading the OpenPose trained models.
        2. Not running OpenPose from the same directory where the `model` folder is located.
        3. Using paths with spaces.

Coming from:
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\net\netCaffe.cpp:op::NetCaffe::ImplNetCaffe::ImplNetCaffe():54
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::addCaffeNetOnThread():131
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\pose\poseExtractorCaffe.cpp:op::PoseExtractorCaffe::netInitializationOnThread():196
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\pose\poseExtractorNet.cpp:op::PoseExtractorNet::initializationOnThread():94
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\src\openpose\pose\poseExtractor.cpp:op::PoseExtractor::initializationOnThread():34
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/pose/wPoseExtractor.hpp:op::WPoseExtractor<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > >::initializationOnThread():50
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/thread/subThread.hpp:op::SubThread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::initializationOnThread():150
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::initializationOnThread():174
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::threadFunction():204
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/thread/thread.hpp:op::Thread<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > >::exec():129
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/thread/threadManager.hpp:op::ThreadManager<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::exec():186
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\include\openpose/wrapper/wrapper.hpp:op::Wrapper<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> >,class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::exec():1072
- D:\Users\Gines\Desktop\OpenPoses\openpose-master\examples\openpose\openpose.cpp:openPoseDemo():372
Can not find pose estimation results

This is strange, because I do have the pose_iter_440000.caffemodel.
Worth to mention that my openpose project works perfectly on it's own. Any suggestions?

Thanks,
Tal

**Comment by yysijie** [comment]
Hi, this codebase has not passed the testing under the Windows System.
The mixture of `/` and `\` in the path may be the reason. See the error message you provided:
```
Caffe trained model file not found: models\pose/coco/pose_iter_440000.caffemodel.
```

**Comment by PratNag** [comment]
You need to manually download or copy the model pose_iter_440000.caffemodel  from OpenPose folder and paste in into the st-gcn/models/pose/coco and it will work. You need the model in the st-gcn models folder.

**Comment by yysijie** [comment]
@PratNag, thank you for your help.
