### ISSUE TITLE
How to know Graph A is correct or not?

### ISSUE THREAD

**Issue by JasOlean** [yysijie/st-gcn#210]
### Other comments
When running Graph.py independently to analyze A value, I got some values with dimension [3,18,18] only in diagonal. So, how to know these values are correct or not?

**Comment by yysijie** [comment]
@JasOlean,
Matrix A is transformed from a graph composed of some edges defined on `graph.py`.
Some third-party packages such as `networkx` may help you to visualize these edges. 
If you implement this function, welcome to submit a pull-request.
