### ISSUE TITLE
Could you provide me Ensemble Model to add ST_GCN to RGB model?

### ISSUE THREAD

**Issue by JasOlean** [yysijie/st-gcn#211]
### Other comments
In your paper, you mentioned about accuracy is increasing when adding ST-GCN to RGB model and optical flow models. 
"We train the standard TSN (Wang et al. 2016) models from scratches on
Kinetics with RGB and optical flow models. Adding STGCN to the RGB model leads to 0.9% increase, even better than optical flows (0.8%)"

So, could you provide me your scripts for ensemble model? Thank you for your help.

**Comment by yysijie** [comment]
@JasOlean,
Sorry, this repo is only for skeleton-based action recognition. We have no plan to provide ensemble model in this codebase. 
We simply add the classification scores of two models together to get an ensemble model, which is easy to be implemented.
