### ISSUE TITLE
How to know training and testing time?

### ISSUE THREAD

**Issue by JasOlean** [yysijie/st-gcn#214]
### Other comments
[07.25.19|15:17:36] Training epoch: 0
[07.25.19|15:17:39] 	Iter 0 Done. | lr: 0.100000 | loss: 6.0831
[07.25.19|15:18:21] 

When I train, I see the time like this.
So, how to know training and testing time?
When I train your kinetics-skeleton data with batch size = 32, I got cuda out of memory RuntimeError after training epoch 4.
RuntimeError: CUDA out of memory. Tried to allocate 1.98 GiB (GPU 0; 7.91 GiB total capacity; 2.70 GiB already allocated; 356.00 MiB free; 3.39 GiB cached)
My GPU memory is 8GB. So, How can I fix this?

**Comment by yysijie** [comment]
training time:
In the default setting, the training will last 50 epochs.
memory problem:
You should also add `--test_batch_size ${test_batch_size}` after the command line to adjust the memory cost in testing state.

**Comment by happysheep224** [comment]
> --test_batch_size
which command should --test_batch_size follow
