### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by LJ0109** [yysijie/st-gcn#215]
When I run the main function, I encountered this problem, how can I solve it? Thank you.

Traceback (most recent call last):
  File "D:/lj/st-gcn-master/main.py", line 28, in <module>
    Processor = processors[arg.processor]
KeyError: None

**Comment by yysijie** [comment]
I think you miss the `processor` item such as `recognition` or `demo`. The correct command is like:
```
python main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml
```
