### ISSUE TITLE
--save-score

### ISSUE THREAD

**Issue by RMobina** [yysijie/st-gcn#24]
### Code version (Git Hash) and PyTorch version
6542289, 0.3.1, running Python 3.6.4

### Dataset used
NTU-RGB-D

### Expected behavior
save the scores

### Actual behavior
Traceback (most recent call last):
  File "/home/ss/eclipse-workspace/CNN_Skeleton_NTURGB/main.py", line 428, in <module>
    processor.start()
  File "/home/ss/eclipse-workspace/CNN_Skeleton_NTURGB/main.py", line 390, in start
    epoch=0, save_score=self.arg.save_score, loader_name=['test'])
  File "/home/ss/eclipse-workspace/CNN_Skeleton_NTURGB/main.py", line 362, in eval
    pickle.dump(score_dict, f)
TypeError: write() argument must be str, not bytes

### Steps to reproduce the behavior
I want save the scores so in the main.py, I changed the default=true as below:
'--save-score',
        type=str2bool,
        default=True,  
        help='if true, the classification score will be stored')

**Comment by yysijie** [comment]
Hi, RMobina,

Thank you for your feedback. This bug has been fixed. 

By the way, you can use this command if you want to save the score.
```
python tools/ntu_gendata.py --data_path <path to nturgbd> --save-score true
```
