### ISSUE TITLE
Improvement / Modification of the model

### ISSUE THREAD

**Issue by bryancresswell** [yysijie/st-gcn#25]
Hi there,

I am looking to improve on the model's structure maybe adding 1 or more layers or something else. How would you suggest I can go about with this? 

Also, the link to your paper returns a 403 Forbidden error. Please advise.

Hope to hear back.

**Comment by yjxiong** [comment]
The paper link seems to be working well on my side. Please try again or use the `cn.arxiv.org` site.

On modification, you can design your own architecture and evaluate it using this framework. For architecture design, I suggest you read previous papers (AlexNet, GoogleNet, ResNet, etc) or textbook on this topic.

**Comment by bryancresswell** [comment]
Alright, thanks!
