### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by liurui16** [yysijie/st-gcn#28]
Thanks for you great work!
When I am learning your work,I came up with the following problem:
### Code version (Git Hash) and PyTorch version
Python 3.6.4 |Anaconda custom (64-bit) 
 dual system: windows & ubuntu 
### Dataset used
kinetics-skeleton
### Expected behavior
Data Preparation:build the database  **Kinetics-Skeleton**  
### Actual behavior
rui@rui-lenovo-xiaoxin-700-15isk:~/Downloads/st-gcn-master$ python tools/kinetics_gendata.py --data_path /media/rui/Study/kinetic-skeleton/kinetics-skeleton
Traceback (most recent call last):
  File "tools/kinetics_gendata.py", line 84, in <module>
    gendata(data_path, label_path, data_out_path, label_out_path)
  File "tools/kinetics_gendata.py", line 54, in gendata
    shape=(len(sample_name), 3, max_frame, 18, num_person_out))
  File "/home/rui/anaconda3/lib/python3.6/site-packages/numpy/lib/format.py", line 763, in open_memmap
    fp = open(filename, mode+'b')
FileNotFoundError: [Errno 2] No such file or directory: 'data/Kinetics/kinetics-skeleton/val_data.npy'
### Steps to reproduce the behavior
I downloaded **Kinetics-Skeleton** from Baidu Yun,unzipped 2 zip segments in Windows disk which has already mounted on Ubuntu.After run the code,I got this FileNotFoundError error.
### Other 
The other dataset **NTU RGB+D** ,which is in the same circumstances as **Kinetics-Skeleton** ,is rebuited well.

**Comment by AndrewSoul** [comment]
Emm.. I have the same problem. Did you solve it?

**Comment by liurui16** [comment]
yes,I created a new folder under /data named"Kinetics",then crated a new folder named "kinetics-skeleton" under /data/Kinetics.Then you can run the code `python tools/kinetics_gendata.py --data_path /media/rui/Study/kinetic-skeleton/kinetics-skeleton`well.
