### ISSUE TITLE
cuda RuntimeError

### ISSUE THREAD

**Issue by guanshanshan** [yysijie/st-gcn#30]
I run this code : python main.py --config  config/st_gcn/nturgbd-cross-subject/test.yaml

  but I recieved this error:

RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at torch/csrc/cuda/Module.cpp:107

How should do  if I want to verify the pretrained model only in CPU?

**Comment by yjxiong** [comment]
```
CUDA driver version is insufficient for CUDA runtime version
```

I think the message is clear here. You could try to install newer CUDA driver and CUDA toolkit.
