### ISSUE TITLE
Question about feeder_kinetics.py

### ISSUE THREAD

**Issue by xiaoyuliu** [yysijie/st-gcn#35]
### Other comments

Hi,

Thanks for the work. I'm using the master branch and trying to understand how you deal with Kinetics dataset. And there's something I'm confused in the script https://github.com/yysijie/st-gcn/blob/master/st_gcn/feeder/feeder_kinetics.py#L72

```python
label_path = self.label_path
with open(label_path) as f:
    label_info = json.load(f)

sample_id = [name.split('.')[0] for name in self.sample_name]
self.label = np.array(
    [label_info[id]['label_index'] for id in sample_id])
has_skeleton = np.array(
    [label_info[id]['has_skeleton'] for id in sample_id])
```

If I don't mistake it, the label file should be `kinetics_train.json` from [this link](https://deepmind.com/documents/66/kinetics_train.zip). And there is no key named `label_index` or `has_skeleton` in the json file, actually the single video's json file has `label_index` but no `has_skeleton` as well.

Does that matter or if I want to evaluate on a new dataset, do I need to create these keys?

Thanks.

**Comment by yjxiong** [comment]
You did mistake it. The label file is generated by
https://github.com/yysijie/st-gcn/blob/master/tools/kinetics_gendata.py

Try reading the README file carefully on how to run the codebase.

**Comment by xiaoyuliu** [comment]
Thank you! And sorry about it.
