### ISSUE TITLE
Hi~Could someone help me? (Kinetics-skeleton)

### ISSUE THREAD

**Issue by AndrewSoul** [yysijie/st-gcn#40]
Hi. I met some problem when I tried to test realtime. Forward to your reply. Thanks in advance!

### Code version (Git Hash) and PyTorch version

pytorch version: 0.3.0

### Dataset used
Kinetics-skeleton

### Expected behavior
Want to test realtime

### Actual behavior

I want to recognize the action in my video. I have used the script tools/convert.py to convert Openpose-format json to st-gcn-format json. ..Then how to feed the converted st-gcn.json file? What does fake_label.json work for? Could you please give me some advice?

### Steps to reproduce the behavior

After using Openpose to treat the original video, I got the output with pose estimation and Openpose-format json files. Then I used the script tools/convert.py to convert Openpose-format json files to st-gcn-format json file and fake_label.json.

**Comment by yysijie** [comment]
I am coming~ Sorry for the late reply.

We release a new version. If you have installed Openpose successfully, the new demo script can directly perform action recognition on your custom videos or wild videos. 

Please git pull the latest master branch and install the codebase.

**Comment by yysijie** [comment]
@AndrewSoul 
Thank you for pointing out it. It works well on my server. Did you run ```cd torchlight``` first before ```python setup.py install```
