### ISSUE TITLE
Help！Memory Error！

### ISSUE THREAD

**Issue by tangjilin** [yysijie/st-gcn#41]
Hi. I met some problem . Forward to your reply. Thanks!
### Dataset used ：
Kinetics-skeleton
###
After rebuilding the database by this command：
python tools/kinetics_gendata.py --data_path <path to kinetics-skeleton>
I got a train_data.npy file which is vrey large(=29G）. Now Iwant to transform it to a  *.mat  file to do my job. However, when I use np.load( ) to load this file ,it showed memory error because it was too big maybe.
What should I do to load the .npy file?Can you help we?Thanks very much!

**Comment by alirezamosh** [comment]
I don't know why you want to convert the file to *.mat but here is my suggestion for training using the proposed pipeline: partition your dataset to smaller ones, train the model on one partition and save the final weight. Then, make the model start to train on a different partition by using the 
saved weights of the previous partition.

**Comment by yjxiong** [comment]
I don't know why you want to do that. But generally, If you feel that you don't have enough memory, use the `mmap_mode` load option. 

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.load.html

@alirezamosh Don't do the thing you described, that will lead to inferior model accuracy unless you only train for a small number of iterations on each partition and train a lot of partitions, which is inefficient.

**Comment by tangjilin** [comment]
Thanks for your help! I will try it.
