### ISSUE TITLE
window_size parameter

### ISSUE THREAD

**Issue by alirezamosh** [yysijie/st-gcn#42]
### Dataset used
Kinetics dataset
### Other comments
In the paper we read that:
> In practice, we represent the clips with tensors of (3, T, 18, 2) dimensions. For simplicity, we pad every clip by replaying the sequence from the start to have T = 300.

If I understand correctly, this T is related to the window_size parameter in the code. However, I am a bit confused as this parameter is used in both the model and the feeder. What exactly is the difference between these two?

**Comment by yjxiong** [comment]
No difference. Feeders need to know how many frames the model expect to input.

**Comment by alirezamosh** [comment]
Maybe I was unclear. What I meant to say was that whether the window_size parameter has different purposes when used in model and feeder. I was wondering about this because in my custom dataset a certain classes have shorter length clips compared to the rest. So I wanted to know if this induces any bias and perhaps modifying the window_size could help in any way.

**Comment by yysijie** [comment]
Hi, @alirezamosh,
The 'window_size' parameter in the feeder is corresponding to T.
In the latest version, we remove this 'window_size' parameter in the model which may result in confusion.
