### ISSUE TITLE
Temporal Bias for Short Videos

### ISSUE THREAD

**Issue by alirezamosh** [yysijie/st-gcn#43]
In my custom dataset, I have a class with clips that are usually 2 or 3 times shorter than the average length of other classes. Since the model pads short clips by repetition to get equal lengths of 300, does this induce a bias in treating shorter clips? Is there a way to address this issue?

Thanks in advance.

**Comment by yysijie** [comment]
@alirezamosh 
Thank you for your interest in our work.
In our implementation, we simply pad zero values if a sequence is too short, and random crop clips if a sequence is too long. 
Zero-padding will increase the computation complexity, but there was no variation observed in our experiments.

**Comment by alirezamosh** [comment]
@yysijie 
Thank you for your answer. This is the most interesting skeleton-based action recognition model that I have read. I think you are referring to `auto_pading` function in the code. But I also see a `window_size` parameter which I think is related to this section in the paper:
> In practice, we represent the clips with tensors of (3, T, 18, 2) dimensions. For simplicity, we pad every clip by replaying the sequence from the start to have T = 300.

In the `feeder.py` and `feeder_kinetics.py`, we have `window_size=-1` and the condition
 `elif self.window_size > 0: `
  `data_numpy = tools.auto_pading(data_numpy, self.window_size)`

I'm a bit confused with how these parameters relate to each other. It would be great if you could elaborate on this.

P.S. There is a new [paper](https://arxiv.org/abs/1805.07694) that builds up on your work and claims superior performance. Just in case you are interested.

**Comment by yjxiong** [comment]
@alirezamosh 

Thanks for the pointer to the paper. Glad the community is welcoming the idea of the spatial-temporal graph.
