### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by jobbofhe** [yysijie/st-gcn#45]
Thanks for your great work!
When I run this project with the following errors:
**System information (version)**
- centos7

- python=3.6.5

```
(pytorch) [root@localhost st-gcn]# python main.py --config config/st_gcn/kinetics-skeleton/test.yaml
[ Wed Jun  6 10:30:43 2018 ] Load weights from ./model/kinetics-st_gcn.pt.
[ Wed Jun  6 10:30:43 2018 ] Model:   st_gcn.net.ST_GCN.
[ Wed Jun  6 10:30:43 2018 ] Weights: ./model/kinetics-st_gcn.pt.
[ Wed Jun  6 10:30:43 2018 ] Eval epoch: 1
0/310
main.py:349: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  volatile=True)
main.py:353: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  volatile=True)
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
```

**Comment by yysijie** [comment]
Hi, thank you for your interest in our project.

Our old code base (v0.1.0) is only for PyTorch (<=0.3.0), please pull the latest master.

**Comment by jobbofhe** [comment]
@yjxiong Oh! I know it , thanks vety much.

**Comment by zahidzqj** [comment]
hi，I want to  know how to train kinetics-skeleton according to the instructions on the official website  use a gpu .     "python main.py recognition -c config/st_gcn/<dataset>/train.yaml"
