### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by lucheng07082221** [yysijie/st-gcn#47]
T run this comman :python3.6 main.py demo --openpose /home/lc/Downloads/openpose-master/cmake-build-debug --video /home/lc/Downloads/st-gcn/resource/media/clean_and_jerk.mp4 --device 0
then got a error
ERROR: unknown command line flag 'display'
ERROR: unknown command line flag 'write_json'
Can not find pose estimation results.

**Comment by yysijie** [comment]
Hi, Lucheng,
It seems that the Openpose version you used is unmatched.
Could you tell me the commit id of your Openpose version?

**Comment by lucheng07082221** [comment]
@yysijie yes ,it is the openpose version's problem.thank you very much!
