### ISSUE TITLE
Can not testing Pretrained Models.

### ISSUE THREAD

**Issue by 124399839** [yysijie/st-gcn#49]
HI!@yysijie @yjxiong
 Thanks for your great work!
 I'm studying your work,but I came up with some problems as follows,could you please give me some hints?
### Code version (Git Hash) and PyTorch version
Use pytorch0.4 version.
### Dataset used
Kinetics-skeleton
`
RuntimeError: Error(s) in loading state_dict for Model:
	Unexpected key(s) in state_dict: "backbone.0.gcn1.mask", "backbone.0.gcn1.conv_list.0.weight", "backbone.0.gcn1.conv_list.0.bias", "backbone.0.gcn1.conv_list.1.weight", "backbone.0.gcn1.conv_list.1.bias", "backbone.0.gcn1.conv_list.2.weight", "backbone.0.gcn1.conv_list.2.bias", "backbone.0.gcn1.bn.weight", "backbone.0.gcn1.bn.bias", "backbone.0.gcn1.bn.running_mean", "backbone.0.gcn1.bn.running_var", "backbone.0.tcn1.conv.weight", "backbone.0.tcn1.conv.bias", "backbone.0.tcn1.bn.weight", "backbone.0.tcn1.bn.bias", "backbone.0.tcn1.bn.running_mean", "backbone.0.tcn1.bn.running_var", "backbone.1.gcn1.mask", "backbone.1.gcn1.conv_list.0.weight", "backbone.1.gcn1.conv_list.0.bias", "backbone.1.gcn1.conv_list.1.weight", "backbone.1.gcn1.conv_list.1.bias", "backbone.1.gcn1.conv_list.2.weight", "backbone.1.gcn1.conv_list.2.bias", "backbone.1.gcn1.bn.weight", "backbone.1.gcn1.bn.bias", "backbone.1.gcn1.bn.running_mean", "backbone.1.gcn1.bn.running_var", "backbone.1.tcn1.conv.weight", "backbone.1.tcn1.conv.bias", "backbone.1.tcn1.bn.weight", "backbone.1.tcn1.bn.bias", "backbone.1.tcn1.bn.running_mean", "backbone.1.tcn1.bn.running_var", "backbone.2.gcn1.mask", "backbone.2.gcn1.conv_list.0.weight", "backbone.2.gcn1.conv_list.0.bias", "backbone.2.gcn1.conv_list.1.weight", "backbone.2.gcn1.conv_list.1.bias", "backbone.2.gcn1.conv_list.2.weight", "backbone.2.gcn1.conv_list.2.bias", "backbone.2.gcn1.bn.weight", "backbone.2.gcn1.bn.bias", "backbone.2.gcn1.bn.running_mean", "backbone.2.gcn1.bn.running_var", "backbone.2.tcn1.conv.weight", "backbone.2.tcn1.conv.bias", "backbone.2.tcn1.bn.weight", "backbone.2.tcn1.bn.bias", "backbone.2.tcn1.bn.running_mean", "backbone.2.tcn1.bn.running_var", "backbone.3.gcn1.mask", "backbone.3.gcn1.conv_list.0.weight", "backbone.3.gcn1.conv_list.0.bias", "backbone.3.gcn1.conv_list.1.weight", "backbone.3.gcn1.conv_list.1.bias", "backbone.3.gcn1.conv_list.2.weight", "backbone.3.gcn1.conv_list.2.bias", "backbone.3.gcn1.bn.weight", "backbone.3.gcn1.bn.bias", "backbone.3.gcn1.bn.running_mean", "backbone.3.gcn1.bn.running_var", "backbone.3.tcn1.conv.weight", "backbone.3.tcn1.conv.bias", "backbone.3.tcn1.bn.weight", "backbone.3.tcn1.bn.bias", "backbone.3.tcn1.bn.running_mean", "backbone.3.tcn1.bn.running_var", "backbone.3.down1.conv.weight", "backbone.3.down1.conv.bias", "backbone.3.down1.bn.weight", "backbone.3.down1.bn.bias", "backbone.3.down1.bn.running_mean", "backbone.3.down1.bn.running_var", "backbone.4.gcn1.mask", "backbone.4.gcn1.conv_list.0.weight", "backbone.4.gcn1.conv_list.0.bias", "backbone.4.gcn1.conv_list.1.weight", "backbone.4.gcn1.conv_list.1.bias", "backbone.4.gcn1.conv_list.2.weight", "backbone.4.gcn1.conv_list.2.bias", "backbone.4.gcn1.bn.weight", "backbone.4.gcn1.bn.bias", "backbone.4.gcn1.bn.running_mean", "backbone.4.gcn1.bn.running_var", "backbone.4.tcn1.conv.weight", "backbone.4.tcn1.conv.bias", "backbone.4.tcn1.bn.weight", "backbone.4.tcn1.bn.bias", "backbone.4.tcn1.bn.running_mean", "backbone.4.tcn1.bn.running_var", "backbone.5.gcn1.mask", "backbone.5.gcn1.conv_list.0.weight", "backbone.5.gcn1.conv_list.0.bias", "backbone.5.gcn1.conv_list.1.weight", "backbone.5.gcn1.conv_list.1.bias", "backbone.5.gcn1.conv_list.2.weight", "backbone.5.gcn1.conv_list.2.bias", "backbone.5.gcn1.bn.weight", "backbone.5.gcn1.bn.bias", "backbone.5.gcn1.bn.running_mean", "backbone.5.gcn1.bn.running_var", "backbone.5.tcn1.conv.weight", "backbone.5.tcn1.conv.bias", "backbone.5.tcn1.bn.weight", "backbone.5.tcn1.bn.bias", "backbone.5.tcn1.bn.running_mean", "backbone.5.tcn1.bn.running_var", "backbone.6.gcn1.mask", "backbone.6.gcn1.conv_list.0.weight", "backbone.6.gcn1.conv_list.0.bias", "backbone.6.gcn1.conv_list.1.weight", "backbone.6.gcn1.conv_list.1.bias", "backbone.6.gcn1.conv_list.2.weight", "backbone.6.gcn1.conv_list.2.bias", "backbone.6.gcn1.bn.weight", "backbone.6.gcn1.bn.bias", "backbone.6.gcn1.bn.running_mean", "backbone.6.gcn1.bn.running_var", "backbone.6.tcn1.conv.weight", "backbone.6.tcn1.conv.bias", "backbone.6.tcn1.bn.weight", "backbone.6.tcn1.bn.bias", "backbone.6.tcn1.bn.running_mean", "backbone.6.tcn1.bn.running_var", "backbone.6.down1.conv.weight", "backbone.6.down1.conv.bias", "backbone.6.down1.bn.weight", "backbone.6.down1.bn.bias", "backbone.6.down1.bn.running_mean", "backbone.6.down1.bn.running_var", "backbone.7.gcn1.mask", "backbone.7.gcn1.conv_list.0.weight", "backbone.7.gcn1.conv_list.0.bias", "backbone.7.gcn1.conv_list.1.weight", "backbone.7.gcn1.conv_list.1.bias", "backbone.7.gcn1.conv_list.2.weight", "backbone.7.gcn1.conv_list.2.bias", "backbone.7.gcn1.bn.weight", "backbone.7.gcn1.bn.bias", "backbone.7.gcn1.bn.running_mean", "backbone.7.gcn1.bn.running_var", "backbone.7.tcn1.conv.weight", "backbone.7.tcn1.conv.bias", "backbone.7.tcn1.bn.weight", "backbone.7.tcn1.bn.bias", "backbone.7.tcn1.bn.running_mean", "backbone.7.tcn1.bn.running_var", "backbone.8.gcn1.mask", "backbone.8.gcn1.conv_list.0.weight", "backbone.8.gcn1.conv_list.0.bias", "backbone.8.gcn1.conv_list.1.weight", "backbone.8.gcn1.conv_list.1.bias", "backbone.8.gcn1.conv_list.2.weight", "backbone.8.gcn1.conv_list.2.bias", "backbone.8.gcn1.bn.weight", "backbone.8.gcn1.bn.bias", "backbone.8.gcn1.bn.running_mean", "backbone.8.gcn1.bn.running_var", "backbone.8.tcn1.conv.weight", "backbone.8.tcn1.conv.bias", "backbone.8.tcn1.bn.weight", "backbone.8.tcn1.bn.bias", "backbone.8.tcn1.bn.running_mean", "backbone.8.tcn1.bn.running_var", "gcn0.mask", "gcn0.conv_list.0.weight", "gcn0.conv_list.0.bias", "gcn0.conv_list.1.weight", "gcn0.conv_list.1.bias", "gcn0.conv_list.2.weight", "gcn0.conv_list.2.bias", "gcn0.bn.weight", "gcn0.bn.bias", "gcn0.bn.running_mean", "gcn0.bn.running_var", "tcn0.conv.weight", "tcn0.conv.bias", "tcn0.bn.weight", "tcn0.bn.bias", "tcn0.bn.running_mean", "tcn0.bn.running_var", "person_bn.weight", "person_bn.bias", "person_bn.running_mean", "person_bn.running_var". 
	While copying the parameter named "data_bn.weight", whose dimensions in the model are torch.Size([54]) and whose dimensions in the checkpoint are torch.Size([108]).
	While copying the parameter named "data_bn.bias", whose dimensions in the model are torch.Size([54]) and whose dimensions in the checkpoint are torch.Size([108]).
	While copying the parameter named "data_bn.running_mean", whose dimensions in the model are torch.Size([54]) and whose dimensions in the checkpoint are torch.Size([108]).
	While copying the parameter named "data_bn.running_var", whose dimensions in the model are torch.Size([54]) and whose dimensions in the checkpoint are torch.Size([108]).
	While copying the parameter named "fcn.weight", whose dimensions in the model are torch.Size([400, 256, 1, 1]) and whose dimensions in the checkpoint are torch.Size([400, 256, 1]).

`

**Comment by yysijie** [comment]
Hi, @124399839,
It seems like you loaded the old model checkpoint in the new codebase. Please run ```bash tools/get_models.sh``` first.

**Comment by 124399839** [comment]
Hi@yysijie @yjxiong，Thanks for your great work!
我現在已經可以跑通測試程序（python main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml）。
現在在跑Demo程序時出現下面的錯誤，
deeplearning@server:~/code$ python3 main.py demo --openpose ~/project/openpose/build/ --video ./resource/media/skateboarding.mp4
Starting OpenPose demo...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...
OpenPose demo successfully finished. Total time: 17.060792 seconds.
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    p.start()
  File "/home/dl/code/processor/demo.py", line 46, in start
    video = utils.video.get_video_frames(self.arg.video)
  File "/home/dl/code/tools/utils/video.py", line 35, in get_video_frames
    vread = skvideo.io.vread(video_path)
  File "/usr/local/lib/python3.6/dist-packages/skvideo/io/io.py", line 133, in vread
    assert _HAS_FFMPEG, "Cannot find installation of real FFmpeg (which comes with ffprobe)."
AssertionError: Cannot find installation of real FFmpeg (which comes with ffprobe).
出現這個錯誤之後我做了如下檢查：首先單獨測試openpose.bin，是可以檢測人體關鍵骨骼點的。
然後查看data/openpose_estimation/snippets/skateboarding下生成的json文件，我查看每個json文件裏面的內容都是空的，並沒有檢測到關鍵骨骼點的座標，不知道產生錯誤的原因是否和這個有關係。
謝謝！

**Comment by yysijie** [comment]
@124399839, 谢谢你指出这个问题，
I think you should install FFmpeg first. 
Try to run `sudo apt-get install ffmpeg` in your console.
Thank you for your report, and we will add this pre-requirement into README.
