### ISSUE TITLE
I can't download NTU RGB+D

### ISSUE THREAD

**Issue by jackasser** [yysijie/st-gcn#5]
Once I register my email,but they reply me to register Organisation.
Then I reply them that I want to just test st-gcn.
and they don't reply any more.

**Comment by yjxiong** [comment]
We don't hold the license to distribute the dataset. You can provide your organization (university, company, or anything else) to the dataset organizers to get the data.

**Comment by jackasser** [comment]
Thank you!
I try it!

**Comment by GimSungwoo** [comment]
Hello, thanks for your fantastic work.
Did you get the dataset? @jackasser 
I cannot sent a request even. When I submit, the website shows "500 - Internal server error.
There is a problem with the resource you are looking for, and it cannot be displayed."
Do you have other contact information of the institution? @yjxiong 

Many thanks

**Comment by jackasser** [comment]
@GimSungwoo 
Me too.
I was displayed 500 - Internal server error.
So, I just download from Kinetics-skeleton.

I want to know other way to train this program.

**Comment by yjxiong** [comment]
As I said we don’t hold the permission to distribute the dataset. Please send email to the admnistrators or file an issue at their Github page https://github.com/shahroudy/NTURGB-D/

**Comment by GimSungwoo** [comment]
I got it. Thank so much for your help.

**Comment by GimSungwoo** [comment]
In addition, in order to visualize the output (i.e. when input a video or the json file, the system can output the video which tells us the specific recognized action, plus the skeleton), could you probably give me a suggestion or idea to implement?
Many thanks!

**Comment by yysijie** [comment]
@GimSungwoo 
To visualize a video with skeleton annotations, GitHub page https://github.com/shahroudy/NTURGB-D/ gives a good Matlab example. We will also release the code for generating videos we shown in the README soon.

**Comment by GimSungwoo** [comment]
Cool! Thanks very much. I will try it; We are looking forward to your favorable work as well.

**Comment by GimSungwoo** [comment]
As for Kinetics-skeleton dataset, is it exactly the output (Json file) of the Openpose? or you write a code to change the content. Because I've tried Openpose today, and there is one which put the values of x, y, scole together into one array and it produce one json file for every frame rather than only one whole file for the whole video. What I used is the flag --write_keypoint_json.

**Comment by yysijie** [comment]
@GimSungwoo 
Yes. For I/O convenience, we changed the structure and rebuilt database extracted by Openpose.
You can save these data as one whole JSON file or '.npy' file like we did. You can also modify the data feeder to read these disperse JSON files (it will be slow).
