### ISSUE TITLE
How to efficiently load kinetics dataset

### ISSUE THREAD

**Issue by huguyuehuhu** [yysijie/st-gcn#53]
### Code version (Git Hash) and PyTorch version
pytorch4.0
### Dataset used
kinetics
### Expected behavior
1.(use class `Feeder` ):After executed your code [kinetics_gendata.py](https://github.com/yysijie/st-gcn/blob/master/tools/kinetics_gendata.py) , I got   `train_data.npy`,et. Then use `Feeder` class to load:
```
params.train_feeder_args["data_path"] = params.dataset_dir+'kinetics-skeleton'+'/processed/train_data.npy'
dataloader = torch.utils.data.DataLoader(
    dataset=Feeder(**params.train_feeder_args),
    batch_size=params.batch_size,
    shuffle=True,
    num_workers=params.num_workers, pin_memory=False)

```
I will `got out of memory `.Because `train_data.npy` is about 43GB, it too large to load without prefetch.
2. （use class `Feeder_kinetics` ）: this is class is to load data from original XXX.json file.
```
params.train_feeder_args["data_path"] = params.dataset_dir+'/kinetics-skeleton'+'/kinetics_train'
dataloader = torch.utils.data.DataLoader(
                dataset=Feeder_kinetics(**params.train_feeder_args),
                batch_size=params.batch_size,
                shuffle=True,
                num_workers=params.num_workers, pin_memory=False)
```
but by this way, the dataloader is slowly, induced that my model on GPU is always wait for data to compute,the efficiency of GPU is about 50%(too low).
### Actual behavior
So, do you have any ideas to load the kinetis dataset efficiently?Thank you!

**Comment by yysijie** [comment]
@huguyuehuhu,
Thank you for your interest in our work.
Our data loader loads all skeleton data at the beginning of training by default. We have fixed this at the latest version. You have 2 choices to solve your problem.
1. Update to the latest master branch. (recommended)
2. Or, run `python main.py recognition -c config/st_gcn/kinetics-skeleton/train.yaml [--work_dir <work folder>] --train_feeder_args mmap=True --test_feeder_args mmap=True`

**Comment by huguyuehuhu** [comment]
@yysijie Hi, your new version torchlight can not find(or make ) `{self.work_dir}/config.yaml and {self.work_dir}/log.txt` correctly. When run` python main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml`. It only make directory` ./work_dir/recognition/kinetics_skeleton/ST_GCN`, no files. Even I create empty 'config.yaml' and 'log.txt' in it, it still a error, could not find it. Why?

I have print out the `self.work_dir`,
```
    def init_environment(self):
        self.io = torchlight.IO(
            self.arg.work_dir,
            save_log=self.arg.save_log,
            print_log=self.arg.print_log)
        print('---------------')
        print(self.arg.work_dir)
        print(self.arg.save_log)
        print(self.arg.print_log)
        self.io.save_arg(self.arg)
```
 it indeed the right dir: ``
![c lsclnj0qj24nk rn4r0](https://user-images.githubusercontent.com/25881545/42031139-c559e9da-7b07-11e8-9794-1c8396280798.png)
