### ISSUE TITLE
Openpose

### ISSUE THREAD

**Issue by kanza-ali** [yysijie/st-gcn#55]
Hi Sir,

I am very much interested in your project and want to use it for my research purpose. 

Ubuntu: 14.04
CUDA: 8
Python: 3.6

I wanted to see the demo but I have this error. Please help me to understand the issue

![screenshot from 2018-06-26 19 13 19](https://user-images.githubusercontent.com/33715985/41905114-24485880-7975-11e8-983c-088da2b2ac45.png)

**Comment by kanza-ali** [comment]
When I run testing code line: python main.py recognition -c config/st_gcn/kinetics-skeleton/test.yaml

**Comment by yysijie** [comment]
hi, @kanza-ali , what's your pytorch version?

**Comment by kanza-ali** [comment]
I have installed pytorch by conda from here https://pytorch.org/

**Comment by kanza-ali** [comment]
When I run training code: python main.py recognition -c config/st_gcn/kinetics-skeleton/train.yaml

It gives me this error: File "/home/kanza/anaconda3/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg/torchlight/gpu.py", line 35, in occupy_gpu
RuntimeError: CUDA error (10): invalid device ordinal

**Comment by yysijie** [comment]
@kanza-ali, yes, you can appoint gpus by `--device`
`python main.py recognition -c config/st_gcn/kinetics-skeleton/train.yaml --device 0 1`
