### ISSUE TITLE
Intra-frame adjacency matrix based 18 human key points in kinetics

### ISSUE THREAD

**Issue by pinkfloyd06** [yysijie/st-gcn#58]
Hello,

How did you get the coordinates of 18 human joints and how did you build the adjacency matrix given these 18 human key points ?
 I don't find the code related to this part in your github. Let me know if l'm missing some thing.

Than kouy for your work.

**Comment by pinkfloyd06** [comment]
Hi @yysijie ,

Thank you for your answer. It is still not clear for me because the adjacency matrix (spatial /intra-frame) follows the human body connectivity as defined in https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md#pose-output-format-coco

Let's consider Pose Output Format (COCO) of 18 key points 
![keypoints_pose_18](https://user-images.githubusercontent.com/17967029/43689369-c2e85c3a-98f9-11e8-851d-16ec024cf442.png)

It's associated spatial/intra-frame adjacency matrix 18 x 18 (since we have 18 key points) is just  
![adj](https://user-images.githubusercontent.com/17967029/43689374-d7ca1648-98f9-11e8-9672-cebb0e6ae1a3.png)

Do you agree ?

Thank you

**Comment by yysijie** [comment]
@pinkfloyd06, sorry for the late reply.
yes, you are right, but it should be further normalized.
