### ISSUE TITLE
Cannot download pretrained model

### ISSUE THREAD

**Issue by tracer9** [yysijie/st-gcn#6]
Hi sijie:
I try to run your program. However  i cannot download your pretrained model due to the GFW in chinese mainland. Could you please provide pretrained models in Baidu Yun or other way.

With much of thanks.

**Comment by yjxiong** [comment]
@yysijie 
Please take a look an see if we can use Baidu Cloud.

**Comment by yysijie** [comment]
Sure, coming soon.

**Comment by yysijie** [comment]
@tracer9 
Hi, Li bin,
We have released pretrained models in BaiduYun.  Please find the model weights and the dataset [here](https://pan.baidu.com/s/1dwKG2TLvG-R1qeIiE4MjeA#list/path=%2FShare%2FAAAI18&parentPath=%2FShare).

**Comment by pingqi** [comment]
@yysijie Hi, I cannot download your pretrained model due to https://s3-us-west-1.amazonaws.com/yysijie-data/public/st-gcn/models/, and I cannot open the link of BaiduYun.

**Comment by yysijie** [comment]
@pingqi, hi, please download [here](https://pan.baidu.com/s/1dwKG2TLvG-R1qeIiE4MjeA#list/path=%2FShare%2FAAAI18%2Fst-gcn%2Fmodels&parentPath=%2FShare).
Then put them into ```./models```
