### ISSUE TITLE
softmax --> svm

### ISSUE THREAD

**Issue by Mitchell1314** [yysijie/st-gcn#62]
Hi,
  I have an idea that I want change your softmax classifier to SVM classifier. Can you tell me where I can do it? Thanks a lot! Waiting for your reply!

**Comment by yysijie** [comment]
Hi, @Mitchell1314,
Thank you for your interest in our works.
Do you mean a SVM classifier with the input of  ST-GCN feature?
You can train a normal ST-GCN. Then, extract the features before the softmax layer.
