### ISSUE TITLE
### Steps to reproduce the behavior

### ISSUE THREAD

**Issue by Emma-99** [yysijie/st-gcn#63]
### Steps to reproduce the behavior
Hello, I have the following problems when running your program.Can you help me with that? Thank you
![image](https://user-images.githubusercontent.com/37145701/42620916-ef1445c6-85ee-11e8-8e9c-0c9911173fff.png)
I use the   Ubuntu 16.04、 Pytorch0.4.0、Python3.5.0.

**Comment by Emma-99** [comment]
I do appreciate the reply you have shown to me.
After reinstalling torchlight, the above problem was solved. The following problems occurred when I tried to  retrain the model. How many gpus did you use? I use two 1080Ti ,is that enough?
![image](https://user-images.githubusercontent.com/37145701/42796235-4e433ed8-89bb-11e8-86e2-6854045e65a1.png)

**Comment by yysijie** [comment]
@Emma-99, 
sorry for the late reply.
You can use a smaller batch size to lower memory requirement. Just add --batch_size <int> and --test_batch_size <int> in the command line.
