### ISSUE TITLE
Extending to real time / multiple actions in a video

### ISSUE THREAD

**Issue by jay-kob** [yysijie/st-gcn#65]
I love the work you've done with the action recognition of a skeleton. I was wondering if you've considered extending it to real time (assuming the poses could be calculated in real time)?

I can see that during the demo predictions are provided on the fly, with a final prediction produced for the video. For non-localised actions then, or for multiple actions in a video - would there be a way to extend the st-gcn to be able to predict them?

**Comment by yysijie** [comment]
Hi, @jay-kob,
The backbone model we used is a convolutional networks, which does support real time inference.
To extending the model to real time, **casual convolution** should be introduced into our st-gcn.
It's not very difficulty. What you should do is to replace all both-side padding operations to left-side padding operations in the st-gcn model. And the inference strategy should also be modified.

**Comment by intvo** [comment]
Can you please add the real-time using webcam camera to your code? 
Thanks

**Comment by yjxiong** [comment]
@intvo 
We don't currently have time for this. You are more than welcome to submit a PR.
