### ISSUE TITLE
Tensor representation of Clip 

### ISSUE THREAD

**Issue by pinkfloyd06** [yysijie/st-gcn#67]
Hello @yysijie and  @yjxiong,

Let me first thank you for your valuable work.

I have a question about ST-GCN input. 

 You mentioned in THE PAPER SECTION 4.1 that the input tensor is (3,T,18,2). Such that T is the number of frames, 18 key points,  2 is coordinate (x,y) of each key point, What is 3 ? , and where the confidence score for each for each human key point ?

Thank you a lot

**Comment by yjxiong** [comment]
The convention is 
[Channel, Time, Joints, Person]

So the first 3 contains `x y confidence` of the joint detection. The last 2 means we use at most 2 persons if there are multiple skeleton detection results in the frame.
