### ISSUE TITLE
Why there are samples_with_missing_skeletons

### ISSUE THREAD

**Issue by LiYachun** [yysijie/st-gcn#69]
I felt a little confused about the samples with missing skeletons. I tried to understand how you selected those samples like:

1. samples of all zeros (165 samples)
2. samples where some frames have no skeleton data (additional 65)

But I didn't manage to figure out how you ignore 302 samples in total. I was wondering if you could give some explanation about those ignored sample. Thank you :)

**Comment by yjxiong** [comment]
Which dataset are you talking about?

**Comment by LiYachun** [comment]
Sorry for the ambiguity. It's about NTU-RGB+D dataset.
