### ISSUE TITLE
what should i do if i want to evaluate ST-GCN on my dataset?

### ISSUE THREAD

**Issue by FesianXu** [yysijie/st-gcn#7]
Hi !
I want to evaluate this model on my own multi-view skeleton dataset without changing the origin code too much. I have skimmed through the codes and i think i should modify class `Feeder`. However i really dont know where to begin to modify it. Could you give me some suggestions? Thanks 
BTW, the shape of the data should be (N, C, T, V, M) and T is the length of the sequence. However the length of the video clip is not equal.  So have you do some sampling ?

**Comment by yysijie** [comment]
Hi, FesianXu,
You can directly employ the default feeder without any modification. 
To generate the database (*data.npy and *label.pkl) for the feeder, please refer to
https://github.com/yysijie/st-gcn/blob/99163728404fcf536912d1e045cfb62eb544ab91/tools/ntu_gendata.py#L77

On your second question, we use the different method to process data in the different dataset.
In the NTU-RGB+D, we simply pad the sequences with zeros and ensure the final length of each sequence is equal.
In the Kinetics-skeleton, we random sample sub-sequence with the same window size. Please refer to
https://github.com/yysijie/st-gcn/blob/99163728404fcf536912d1e045cfb62eb544ab91/st_gcn/feeder/tools.py#L42

**Comment by FesianXu** [comment]
Thanks for your response. It really helps.
