### ISSUE TITLE
How can I count the number of push-up I didi in the video?

### ISSUE THREAD

**Issue by caoxudong** [yysijie/st-gcn#70]
### Code version (Git Hash) and PyTorch version

code version: c56021c
pytorch version: 1.0

### Dataset used

Kinetics-skeleton

### Expected behavior

count the number of push-ups

### Actual behavior

None

### Other comments

Hi, guys

Thanks for your work. I'm using st-gcn to do video analyzing, and got the label of the pose. Furthermore, could I get the number of push-ups I did in the video?

Any comments will be much appreciated

**Comment by yjxiong** [comment]
My guess is you can start with treat different numbers as classes and do classification. The you can iterate on better ideas.
