### ISSUE TITLE
Reproducing Results on Kinetics-Motion subset

### ISSUE THREAD

**Issue by hermanprawiro** [yysijie/st-gcn#74]
Hi, I'm trying to reproduce the result in your paper. I have several questions.

On the result in the "Kinetics Motion" subset (which is a subset of 30 classes strongly related with body motions), do you train using full 400 classes and then test on 30 classes, or train and test on the 30 classes subset?

Can you list the name of the 30 classes in the "Kinetics Motion" subset?

Thank you.

**Comment by yysijie** [comment]
Hi, we trained on full 400 classes and then test on 30 classes. 
Please refer to this link for the name of 30 classes:
https://github.com/yysijie/st-gcn/blob/master/resource/kinetics-motion.txt

**Comment by hermanprawiro** [comment]
I see. Thanks for your response!
