### ISSUE TITLE
 Why 2D pose estimation is not as accurate as 3D ?

### ISSUE THREAD

**Issue by pinkfloyd06** [yysijie/st-gcn#75]
Hello, @yysijie 

Let me first thank you for your work. 

 Why 2D pose estimation is not as accurate as 3D ?

Thank you

**Comment by yjxiong** [comment]
It’s not as simple as something is not “accurate” as something. There are a lot of factors affecting the accuracy. Just to name a few, the number of classes and the devices for aquaring the data. 

Plus, “issues” is preferred for raising issues about code bugs and usage questions. Please kindly follow this convention and do not abuse it.
