### ISSUE TITLE
how to do multi-action recognition in a video

### ISSUE THREAD

**Issue by taxuezcy** [yysijie/st-gcn#76]
@yjxiong  @yysijie ,
thank you for your great work, i have tested you model and run the demo, i found that i can only get one action class for one video, but one video was made up of many actions,so can your model do some related work like that? looking forward to your reply

**Comment by yysijie** [comment]
@taxuezcy,
Hi, 
In the demo script, this sentence get scores of all action classes at different frames of a video:
https://github.com/yysijie/st-gcn/blob/2214414c61c56cfc4eb1320ba607af14a3a086e4/processor/demo.py#L70
After that, we average scores of all frames to get the final result. You can fix this step to get the multiple action classes in one video.

**Comment by taxuezcy** [comment]
@yysijie , thank you every much, i have used you method ,and got the action  of every frame

**Comment by CompliceU** [comment]
Hello, I am also trying this work recently. I don't know if I can guide you. Thank you. @taxuezcy

**Comment by vinayaksun** [comment]
@CompliceU If you can please guide me?

**Comment by SKBL5694** [comment]
> Hello, I am also trying this work recently. I don't know if I can guide you. Thank you. @taxuezcy

Hello，I met some mistakes, are you convenient to give me some help？
