### ISSUE TITLE
gendata format

### ISSUE THREAD

**Issue by sjtuxcx** [yysijie/st-gcn#77]
Hello! First thanks for the code. Can you explain the format of  train_data,npy and train_label.pkl? Thanks a lot!

**Comment by yysijie** [comment]
Hi, 

train_data.npy is a Numpy array with the shape of (N,C,T,V,M), where:
N: number of samples
C: number of channels
T: number of video frames/ length of the sequence
V: number of human joints
M: number of persons

train_label.pkl is a tuple which has two elements, the first one is the name list of N samples, 
the second one is the action label index of N samples.

**Comment by yanqian123** [comment]
what is "number of channels"?? we know about one image,3 channels means RGB ,but in this .npy file what is the meaning? @sjtuxcx @yysijie

**Comment by yysijie** [comment]
@yanqian123, it usually means spatial coordinates 'x,y,z' of each joint.
