### ISSUE TITLE
when i run this script ,i get thie issues ,what makes that happen ?kinetics_gendata.py --data_path /home/vincent/文档/kinetics-skeleton 

### ISSUE THREAD

**Issue by Vincent630** [yysijie/st-gcn#79]
(venv) vincent@vincent:~/st-gcn$ python tools/kinetics_gendata.py --data_path /home/vincent/文档/kinetics-skeleton
Traceback (most recent call last):----                        ]
  File "tools/kinetics_gendata.py", line 87, in <module>
    gendata(data_path, label_path, data_out_path, label_out_path)
  File "tools/kinetics_gendata.py", line 58, in gendata
    data, label = feeder[i]
  File "/home/vincent/st-gcn/feeder/feeder_kinetics.py", line 125, in __getitem__
    assert (self.label[index] == label)
AssertionError

**Comment by Vincent630** [comment]
i fix this problem because someones has do for this, if you have the same problem,you can ask me and i will help you .

**Comment by gds123456** [comment]
i have met this problem,can you help me?

**Comment by Joye-hss** [comment]
Excuse me, how did you solve this problem? Looking forward to your reply. Thank you.
