### ISSUE TITLE
Inference on personal data

### ISSUE THREAD

**Issue by Chevrefeuille** [yysijie/st-gcn#8]
Hi! First of all thanks for this great project.
I am currently working on a project where I want to detect specific actions performed by pedestrians and I thought that your code could provide me a great starting point.
Currently I am using **OpenPose** to extract two skeleton estimations from 10sec video clips at 30fps.
From what I have seen the JSON output format provided by OpenPose is a bit different from the input format of your network. I am planning on writing a script to convert the results to the right format, I just wanted to be sure that I was not missing anything. 
Similarly, I believe that I need to modify slightly your code to add a method to generate predictions without labels provided (which I believe is the case in both eval and train method). Am I right with this?
Thanks for your thoughts!

**Comment by yysijie** [comment]
Hi, Adrien,

Thanks for your interest in our work.
Actually, we use different data loader in the learning of different dataset.
The data loader for Kinetics read JSON files we provided and output
skeleton sequences and labels.
The data loader for NTU-RGB-D read "*data.npy" and "*label.pkl" file to
generate data and groundtruth.
If you don't want to rewrite data feeder, please refer to
tools/ntu_gendata.py. You should transform your data like we did in this
script and directly use default data loader  feeder.py in the learning. You
can also write a new data feeder if you want. But I do not recommend you
directly read JSON files provided by OpenPose. These files are too small.
The I/O cost is pretty high.
Of cause, you can also convert these JSON files to the format we defined
and directly use feeder_kinetics.py as you said. You do not need to modify
my code. Just provide one fake label for each sample.

Bests,
Sijie

2018-03-19 14:24 GMT+08:00 Adrien Gregorj <notifications@github.com>:

**Comment by Chevrefeuille** [comment]
Thanks for the fast answer Sijie!
I thought that you had done something similar to create your Kinetics-skeleton data. I will go and write a script to convert OpenPose JSON format to the right one.
Yes it is indeed simpler to use fake labels. 
Best regards,
Adrien

**Comment by coldmanck** [comment]
Hi @Chevrefeuille 

May I know have you written the script converting from OpenPose JSON format to their input format? If so may I have a copy so that I can avoid reinventing the wheel? :-)

**Comment by Chevrefeuille** [comment]
Hi @coldmanck !
Yes I have written this script, here is a copy of it (some parts like the name of the file are specific to my current project but the global idea might already be interesting for you): 
```python
import os
from pathlib import Path
import json
from pprint import pprint

if __name__ == "__main__":
    folder = '2010_10_06'
    p = Path('../data/poses/openpose_format')
    list_data_file = '../data/data_list.dat'
    labels = {}
    with open(list_data_file, 'r') as f:
        for line in f:
            vid  = int(line)
            j = 0               
            stgcn_data_array = []
            stgcn_data = {}
            dest_path = '../data/poses/st-gcn_format/' + str(vid) + '.json'
            for path in p.glob(str(vid) + '*.json'): # each json file
                json_path = str(path)
                j += 1
                frame_id = int(((json_path.split('/')[-1]).split('.')[0]).split('_')[1])
                frame_data = {'frame_index': frame_id}
                data = json.load(open(json_path))
                skeletons = []        
                for person in data['people']:
                    score, coordinates = [], []
                    skeleton = {}
                    keypoints = person['pose_keypoints_2d']
                    for i in range(0,len(keypoints),3):
                        coordinates +=  [keypoints[i], keypoints[i + 1]]
                        score += [keypoints[i + 2]]
                    skeleton['pose'] = coordinates
                    skeleton['score'] = score
                    skeletons += [skeleton]
                frame_data['skeleton'] = skeletons
                stgcn_data_array += [frame_data]
            if j == 300:
                labels[str(vid)] = {"has_skeleton": True, 
                    "label": "fake_label", 
                    "label_index": 0}
                stgcn_data['data'] = stgcn_data_array
                stgcn_data['label'] = 'fake_label'
                stgcn_data['label_index'] = 0
                with open(dest_path, 'w') as outfile:
                    json.dump(stgcn_data, outfile)

    labels_file = '../data/poses/fake_labels.json'
    with open(labels_file, 'w') as label_file:
        json.dump(labels, label_file)
```
I am not a python export so any comment are well appreciated 😄 . The condition `j == 300` is due to an issue that I have with my input videos that are not always 300 frame long but you can probably assume that yours are.

**Comment by coldmanck** [comment]
Hi @Chevrefeuille 

Thanks for the fast reply and the amazing script! I will try it and give feedback, if any :)

**Comment by yjxiong** [comment]
@Chevrefeuille 
Thanks for the nice scripts! Do you mind contributing the script to the codebase? This way al users can benefit from your work. You are more than welcome to open a pull request.

**Comment by Chevrefeuille** [comment]
I would be glad to do so, I will just make a few adjustments to have it less specific.

**Comment by xiaoyuliu** [comment]
Hi @Chevrefeuill ,

Thanks for your scripts to convert Openpose output into ST-GCN format! I have several suggestions for [the script](https://github.com/yysijie/st-gcn/blob/master/tools/convert_poses.py)

line 14
```python
for path in p.glob('*.avi'):
    f.write(path.stem + '\n')
```
Basically `path.stem` will return the file's name without the suffix

line 45
```python
dest_path = os.path.join(arg.stgcn_json_path, video_name + '.json')
```
In case the `arg.stgcn_json_path` contains no `/`

line 48
```python
frame_id = int(path.stem.split('_')[1])
```

**Comment by yjxiong** [comment]
@xiaoyuliu 
Please send a PR.

**Comment by xiaoyuliu** [comment]
@yysijie 
Thanks, I will create one for that soon. Actually I'd like to add one function `top_k_by_category` to display the accuracy for each category, should I do that in the same PR? (If you think it's ok to add the function)
