### ISSUE TITLE
RuntimeError: CUDA error (10): invalid device ordinal

### ISSUE THREAD

**Issue by Vincent630** [yysijie/st-gcn#80]
when i train on my GTX1060(ONLY 1 GPU),I get this problem,i konw maybe that is a gpus number problem,but how to fix this problem,please help me and i would preciate that.

/home/vincent/venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    p = Processor(sys.argv[2:])
  File "/home/vincent/st-gcn/processor/processor.py", line 29, in __init__
    self.init_environment()
  File "/home/vincent/st-gcn/processor/processor.py", line 38, in init_environment
    super().init_environment()
  File "/home/vincent/st-gcn/processor/io.py", line 62, in init_environment
    torchlight.occupy_gpu(gpus)
  File "/home/vincent/venv/lib/python3.6/site-packages/torchlight-1.0-py3.6.egg/torchlight/gpu.py", line 35, in occupy_gpu
RuntimeError: CUDA error (10): invalid device ordinal

**Comment by Vincent630** [comment]
that is a easy problem but still take my some time to fix this ,you can just set your gpus to do this ,
just like this : -- device 0

**Comment by nainadhingra2012** [comment]
@Vincent630 I am also facing the same error. Can you please tell what changes did you do to resolve it? Where do you write --device 0?

**Comment by YuxuanSnow** [comment]
> @Vincent630 I am also facing the same error. Can you please tell what changes did you do to resolve it? Where do you write --device 0?

 you can appoint gpus by --device, for example: python main.py recognition -c config/st_gcn/kinetics-skeleton/train.yaml --device 0
