### ISSUE TITLE
How did you handle variable length videos to build adjacency matrix ?

### ISSUE THREAD

**Issue by pinkfloyd06** [yysijie/st-gcn#85]
Hi @yysijie,

Kinetics is characterised by a variable length videos. I'm wondering how you cope with variable number of frames to build your adjacency matrix.

Are you sampling K frames from each video ? or you zero-padd the adjacency matrix ?

Thank you for your answer

**Comment by yysijie** [comment]
@pinkfloyd06, 
Yes, @zhezh is right. Actually, both methods you mentioned are ok. We random cropped sequences on **kinetics-skeleton** dataset and zero-padded sequences on **NTU-RGB-D** dataset since these sequences are much shorter.

**Comment by pinkfloyd06** [comment]
@zhezh & @yysijie ,
Thank you for your asnwer. So how many frames you take from each video ?

**Comment by yysijie** [comment]
@pinkfloyd06, 128 frames.

**Comment by pinkfloyd06** [comment]
Thank you for your answer @yysijie . Did you take the first 128 frames or sample  randomly 128  from the whole video ?

**Comment by yjxiong** [comment]
@pinkfloyd06 In the training, the 128 frames are sampled consecutively from a random starting position.

**Comment by pinkfloyd06** [comment]
@yjxiong  in the test you take the first 128 frames ?

**Comment by yjxiong** [comment]
In testing, all frames are used. Please carefully read the paper for these details.
