### ISSUE TITLE
about the Temporal Part in st-gcn

### ISSUE THREAD

**Issue by yanqian123** [yysijie/st-gcn#88]
@yysijie @yjxiong hello, thank you for your sharing about the network, as a new student in this field, I want to ask you "how to add the temporal information in the graph ? " in the graph.py, i only saw the adjacency matrix about the 18 points in openpose, but i don't know your method to add the temporal information in the graph, could you give me some advice, of course as a beginner,i am looking for your reply, thanks again

**Comment by yysijie** [comment]
In our implementation, we follow the idea from the separable convolution. We used a common 1d convolution to process the temporal information ( a joint track) and a graph convolution to process spatial information (a human skeleton in a frame). 

You can also process them simultaneously. Please refer to https://github.com/yysijie/st-gcn/blob/master/net/utils/tgcn.py.  ```ConvTemporalGraphical```is the graph convolution layer we used. You can assign  ```t_kernel_size ```  parameter  to modify the kernel size in the time dimension. The default value is 1.

**Comment by yanqian123** [comment]
thanks a lot, i will see the code again.
