### ISSUE TITLE
tools/ntu_gendata write error

### ISSUE THREAD

**Issue by zhezh** [yysijie/st-gcn#9]
the line 77
`with open('{}/{}_label.pkl'.format(out_path, part), 'w') as f:`

should be fixed as:
`with open('{}/{}_label.pkl'.format(out_path, part), 'wb') as f:`

to avoid error: must be str, not bytes

refer: https://stackoverflow.com/questions/13906623/using-pickle-dump-typeerror-must-be-str-not-bytes

**Comment by yysijie** [comment]
Thank you! The error has been fixed.

**Comment by taxuezcy** [comment]
@zhezh  ,how can you get the ntu dataset? i cannot download it and  i will be very grateful if you can send me, my email is zcytaxue@163.com,
