### ISSUE TITLE
您好，请问我应该用openpose的什么设置来获得骨架关键点检测的json结果。因为我下载了您提供的训练数据集，里面的内容和我通过openpose获得的结果不一样。您是怎么设置的。希望能得到您的回复。谢谢。

### ISSUE THREAD

**Issue by HuangSanLi** [yysijie/st-gcn#90]

**Comment by yysijie** [comment]
Hi, @HuangSanLi,
Please refer to https://github.com/yysijie/st-gcn/blob/master/tools/utils/openpose.py
This function transforms the JSON files extracted by openpose into our format.

**Comment by HuangSanLi** [comment]
thanks so much.You are so freindly.

**Comment by yanqian123** [comment]
@HuangSanLi 你好，请问你弄明白啦么？我想在自己的数据集上训练模型，但是在数据转换成JSON的时候不是很明白，能和您交流一下么？

**Comment by HuangSanLi** [comment]
应该就是用这个函数https://github.com/yysijie/st-gcn/blob/master/tools/utils/openpose.py将一段视频所有帧整合到一个文件里 。

**Comment by HuangSanLi** [comment]
您好！问您个问题，就是在用自己的数据集时，代码中的label是怎么获得的，所对应的内容/格式是什么。谢谢@yanqian123。就是我要使用kinetics_gendata.py 代码。

**Comment by yanqian123** [comment]
@HuangSanLi 格式是自己做的，文件夹里有val_label.json的文件，看着他的格式生成就可以

**Comment by 124399839** [comment]
@yanqian123 您好，我現在也在使用自己的數據進行訓練ST-GCN,但是在生成val_label.json上出現問題，可以將生成val_label.json文件的腳本發給我參考一下嗎？謝謝，郵箱124399839@qq.com
