### ISSUE TITLE
scripts for Ensemble model

### ISSUE THREAD

**Issue by sophia-wright-blue** [yysijie/st-gcn#91]
### Code version (Git Hash) and PyTorch version

PyTorch: 0.4

### Dataset used

Kinetics

### New query

Thank you for releasing the code and for providing detailed guidelines for using the scripts. In your paper, you mention that you also added ST-GCN to an RGB model trained on Kinetics (the Ensemble model in Table 5). I was wondering if you've also released the scripts to create and test the Ensemble model?

 I expect to have a model trained on the RGB frames of the Kinetics dataset soon. Can you point me to any scripts that I can use to add ST-GCN to an RGB model to create an Ensemble model? Or provide me with some guidelines to do the same?

Thank you,

**Comment by yjxiong** [comment]
To perform the ensemble, you can put the output of your models in the format of TSN toolkit. And use the `eval_score.py` script in the toolkit for the ensemble.

https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/eval_scores.py

**Comment by sophia-wright-blue** [comment]
thank you for replying @yjxiong , I'll give that a shot soon, and thank you also for making so much useful code available for use

**Comment by sophia-wright-blue** [comment]
Hi @huanglai666 , thanks for reaching out, unfortunately, i've gotten sidetracked  by other projects, i do hope to get back to this though, will let you know if I make any progress,
