### ISSUE TITLE
  AssertionError     ~/st-gcn/st-gcn$ python tools/kinetics_gendata.py --data_path ~/kinetics-skeleton

### ISSUE THREAD

**Issue by Joye-hss** [yysijie/st-gcn#92]
Sorry to bother you, I get an error when I run this command：
##haoshanshan@BJTU-PSC-6S-1080:~/st-gcn/st-gcn$ python tools/kinetics_gendata.py --data_path ~/kinetics-skeleton
Traceback (most recent call last):--                          ]
  File "tools/kinetics_gendata.py", line 87, in <module>
    gendata(data_path, label_path, data_out_path, label_out_path)
  File "tools/kinetics_gendata.py", line 58, in gendata
    data, label = feeder[i]
  File "/home/haoshanshan/st-gcn/st-gcn/feeder/feeder_kinetics.py", line 125, in __getitem__
    assert (self.label[index] == label)
AssertionError

So I would like to ask you how to solve it?Looking forward to your reply.Thank you!

**Comment by Joye-hss** [comment]
Need your help.If the '--data_path' is 'data/Kinetics/kinetics-skeleton' in the kinetics_gendata.py ?Should I rebuild the kinetics-skeleton in the path ~/st-gcn/data/Kinetics/kinetics-skeleton ?@yjxiong @yysijie

**Comment by yangwenzhe** [comment]
I met the same bug just now,can you share how to solve this problem?thank a lot

**Comment by yangwenzhe** [comment]
sorry,I download this "kinetics-skeleton" dataset in baiduyun
when I run this command：
python tools/kinetics_gendata.py --data_path ~/kinetics-skeleton
Traceback (most recent call last):-- ]
File "tools/kinetics_gendata.py", line 87, in 
gendata(data_path, label_path, data_out_path, label_out_path)
File "tools/kinetics_gendata.py", line 58, in gendata
data, label = feeder[i]
File "/home/haoshanshan/st-gcn/st-gcn/feeder/feeder_kinetics.py", line 125, in getitem
assert (self.label[index] == label)
AssertionError

So I would like to ask you how to solve it?Looking forward to your reply.Thank you! @yysijie

**Comment by yysijie** [comment]
@Joye-hss, @yangwenzhe, @simonggx,
I still can not replicate the bug you mentioned. I provide my steps here for your reference.
1. Update the codebase to the latest version.
2. Download data from [GoogleDrive](https://drive.google.com/drive/folders/1SPQ6FmFsjGg3f59uCWfdUWI-5HJM_YhZ)(md5 code: e87b86a310070e1b843b29b2965027ea).
3. Extract zip file.
4. Run ```python tools/kinetics_gendata.py --data_path [path to dataset]```. 
I tried python3.5 and 3.6 in this step.

**Comment by liwanjie1020** [comment]
因为我用的anaconda所以命令需要改变一下，不需要<>以及path to 只需要python tools/kinetics_gendata.py --data_path kinetics-skeleton即可
