### ISSUE TITLE
about GPU memory when training

### ISSUE THREAD

**Issue by yanqian123** [yysijie/st-gcn#94]
hello @yysijie @yjxiong  , I am sorry to bother you again. as a beginner, I am not familiar with Pytorch, when i was training ,the GPU memory used 2697MiB, and if the epoch=1,2,3....is the same. But in this moring ,when the epoch=9, the GPU memory used 2845MiB.I want know the reason about it. I guess that in the file, we saved weighs every 10 epoch caused increaseing memory, an i right??? and if when the epoch=11,12,.....,  ,the GPU memory using is 2697MiB or still increaseing until finish training???
thanks again, i am looking for your reply

**Comment by yysijie** [comment]
Hi, @yanqian123,
Thank you for your interest in our works.
The reason is that an extra batch for evaluation will be sampled every 10 epochs.
