### ISSUE TITLE
training on a new dataset

### ISSUE THREAD

**Issue by yanqian123** [yysijie/st-gcn#97]
@yysijie @yjxiong I want to train the st-gcn on another dataset ,so I think I should transform the format so that I can train the model as usual. And there are some questions:
first of all , I think I need to using openpose to generate json files for my dataset, for a video,after using openpose there will be many json files, i think i need to merge them to one json,  i have seen the kinetic dataset's json(7.5G) on your github,the value range is different from openpose,so what should i do ,or i could refer to the code in demo.py ???
      # pack openpose ouputs
        video = utils.video.get_video_frames(self.arg.video)
        height, width, _ = video[0].shape
        video_info = utils.openpose.json_pack(
            output_snippets_dir, video_name, width, height)
        if not os.path.exists(output_sequence_dir):
            os.makedirs(output_sequence_dir)
        with open(output_sequence_path, 'w') as outfile:
            json.dump(video_info, outfile) as : 
then about the video length in my dataset is different ,you said about your training, the length=300,so should i do something to let the frame_index about every video's json file to be 300,or it isn't necessary??
could you tell me what should i do about my dataset? thanks again, as a new in this field ,i feel very lucy to communcate with you

**Comment by yysijie** [comment]
Hi, @yanqian123,
Please refer to
https://github.com/yysijie/st-gcn/blob/6796c960d67f6b341804f52122e46d8bcb0526bd/processor/demo.py#L49-L50
. This is the statement for transform the format.

On your second question, zero-padding is OK.
You can also recurrently flip your sequence and concatenate them together.
For example, if you have a sequence [1,2,3,4,5], then you can create a infinite sequence which has the form:
[1,2,3,4,5,4,3,2,1,2,3,4,5,4,3,2...]

**Comment by yanqian123** [comment]
thank you , the answer you given me is  very useful , now I know it clearly ， thanks again
