### ISSUE TITLE
about kinetics_train_label.json

### ISSUE THREAD

**Issue by yanqian123** [yysijie/st-gcn#98]
@yysijie hello, I have found in the kinetice_train_label.json, there is a key named: "has_skeleton" 
sometimes it is true,sometimes,it is false, what is the meaning about the value?????
as you know, I want to use my own dataset to train, when I translating the dataset, I was confused by the label json file.....

**Comment by yanqian123** [comment]
if it means that openpose could not estimate pose on the related video???

**Comment by HuangSanLi** [comment]
Can you tell me where the kinetice_train_label.json is?Thanks!

**Comment by yanqian123** [comment]
@HuangSanLi in this Kinetics-skeleton(7.5GB) package,
