### ISSUE TITLE
how to set "openpose build directory"?

### ISSUE THREAD

**Issue by cuixing158** [yysijie/st-gcn#99]
how to set "openpose build directory"?Can you be more specific? my pc is win10，all other requirements have succeffully instaled. thankyou

**Comment by unbiasedmodeler** [comment]
take a look at the code in https://github.com/yysijie/st-gcn/blob/master/processor/demo.py , line 21 is where you feed in the path to the openpose.bin. the default path to self.arg.openpose is specified on line 114. i think the easiest way is to build openpose in a directory (instructions here - https://github.com/CMU-Perceptual-Computing-Lab/openpose) and point to that folder. hope that helps.

**Comment by cuixing158** [comment]
Has been resolved,thanks

**Comment by yysijie** [comment]
Thank you, @unbiasedmodeler.

**Comment by bowrian** [comment]
> Have been resolved,thanks

could you give me your command when you set the "path to the openpose build directory"?thanks!

**Comment by bowrian** [comment]
> Have been resolved,thanks

I don't find the openpose.bin in path "examples/openpose/openpose.bin",please tell me how I can do? thinks @yysijie @yjxiong  @cuixing158 @unbiasedmodeler

**Comment by yysijie** [comment]
@bowrian, please build the openpose first, the installation guideline can be find [here](https://github.com/yysijie/openpose). Usually, Openpose will be defaultly built under ```<openpose path>/build/```. After that, run
```
python main.py demo --openpose <path to openpose build directory> [--video <path to your video> --device <gpu0> <gpu1>]
```

**Comment by bowrian** [comment]
After three days of hard work, finally, debug your code, thank you very much for your answers, thank you!

**Comment by yysijie** [comment]
Hi, @bowrian, did you mean that there is a bug in the codebase? Can't you run the codebase directly after the installation of Openpose?

**Comment by bowrian** [comment]
Yes, I guess the problem with the python version，for example:
In st_gcn.py file index 29th row:
 `def __init__(self, in_channels, num_class, graph_args,
                 edge_importance_weighting, **kwargs):
        super(Model,self).__init__()`
need add Model,self in super(),otherwise, The terminal will display missing parameters in the super() function.When dubug super(Model,self).__init__(),it works.

**Comment by yysijie** [comment]
Oh, it caused by the wrong pytorch version.You can follow the installation
guide in README if you find other running problems.

**Comment by bowrian** [comment]
Ok, thanks for your attention
